/* This file is auto-generated by Forket. Don't change it manually. */

export default function () {
  return {
  "type": "FunctionDeclaration",
  "identifier": {
    "type": "Identifier",
    "span": {
      "start": 758,
      "end": 778
    },
    "ctxt": 2,
    "value": "forketSerializeProps",
    "optional": false
  },
  "declare": false,
  "params": [
    {
      "type": "Parameter",
      "span": {
        "start": 779,
        "end": 784
      },
      "decorators": [],
      "pat": {
        "type": "Identifier",
        "span": {
          "start": 779,
          "end": 784
        },
        "ctxt": 3,
        "value": "props",
        "optional": false,
        "typeAnnotation": null
      }
    }
  ],
  "decorators": [],
  "span": {
    "start": 749,
    "end": 1627
  },
  "ctxt": 3,
  "body": {
    "type": "BlockStatement",
    "span": {
      "start": 786,
      "end": 1627
    },
    "ctxt": 3,
    "stmts": [
      {
        "type": "FunctionDeclaration",
        "identifier": {
          "type": "Identifier",
          "span": {
            "start": 799,
            "end": 813
          },
          "ctxt": 3,
          "value": "isValidElement",
          "optional": false
        },
        "declare": false,
        "params": [
          {
            "type": "Parameter",
            "span": {
              "start": 814,
              "end": 817
            },
            "decorators": [],
            "pat": {
              "type": "Identifier",
              "span": {
                "start": 814,
                "end": 817
              },
              "ctxt": 4,
              "value": "obj",
              "optional": false,
              "typeAnnotation": null
            }
          }
        ],
        "decorators": [],
        "span": {
          "start": 790,
          "end": 1029
        },
        "ctxt": 4,
        "body": {
          "type": "BlockStatement",
          "span": {
            "start": 819,
            "end": 1029
          },
          "ctxt": 4,
          "stmts": [
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 825,
                "end": 855
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 831,
                    "end": 854
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 831,
                      "end": 835
                    },
                    "ctxt": 4,
                    "value": "keys",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "CallExpression",
                    "span": {
                      "start": 838,
                      "end": 854
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 838,
                        "end": 849
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 838,
                          "end": 844
                        },
                        "ctxt": 1,
                        "value": "Object",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 845,
                          "end": 849
                        },
                        "value": "keys"
                      }
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 850,
                            "end": 853
                          },
                          "ctxt": 4,
                          "value": "obj",
                          "optional": false
                        }
                      }
                    ],
                    "typeArguments": null
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "ReturnStatement",
              "span": {
                "start": 860,
                "end": 1025
              },
              "argument": {
                "type": "ParenthesisExpression",
                "span": {
                  "start": 867,
                  "end": 1024
                },
                "expression": {
                  "type": "BinaryExpression",
                  "span": {
                    "start": 875,
                    "end": 1018
                  },
                  "operator": "&&",
                  "left": {
                    "type": "BinaryExpression",
                    "span": {
                      "start": 875,
                      "end": 986
                    },
                    "operator": "&&",
                    "left": {
                      "type": "BinaryExpression",
                      "span": {
                        "start": 875,
                        "end": 953
                      },
                      "operator": "&&",
                      "left": {
                        "type": "BinaryExpression",
                        "span": {
                          "start": 875,
                          "end": 920
                        },
                        "operator": "&&",
                        "left": {
                          "type": "BinaryExpression",
                          "span": {
                            "start": 875,
                            "end": 898
                          },
                          "operator": "===",
                          "left": {
                            "type": "UnaryExpression",
                            "span": {
                              "start": 875,
                              "end": 885
                            },
                            "operator": "typeof",
                            "argument": {
                              "type": "Identifier",
                              "span": {
                                "start": 882,
                                "end": 885
                              },
                              "ctxt": 4,
                              "value": "obj",
                              "optional": false
                            }
                          },
                          "right": {
                            "type": "StringLiteral",
                            "span": {
                              "start": 890,
                              "end": 898
                            },
                            "value": "object",
                            "raw": "\"object\""
                          }
                        },
                        "right": {
                          "type": "BinaryExpression",
                          "span": {
                            "start": 908,
                            "end": 920
                          },
                          "operator": "!==",
                          "left": {
                            "type": "Identifier",
                            "span": {
                              "start": 908,
                              "end": 911
                            },
                            "ctxt": 4,
                            "value": "obj",
                            "optional": false
                          },
                          "right": {
                            "type": "NullLiteral",
                            "span": {
                              "start": 916,
                              "end": 920
                            }
                          }
                        }
                      },
                      "right": {
                        "type": "CallExpression",
                        "span": {
                          "start": 930,
                          "end": 953
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "MemberExpression",
                          "span": {
                            "start": 930,
                            "end": 943
                          },
                          "object": {
                            "type": "Identifier",
                            "span": {
                              "start": 930,
                              "end": 934
                            },
                            "ctxt": 4,
                            "value": "keys",
                            "optional": false
                          },
                          "property": {
                            "type": "Identifier",
                            "span": {
                              "start": 935,
                              "end": 943
                            },
                            "value": "includes"
                          }
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "StringLiteral",
                              "span": {
                                "start": 944,
                                "end": 952
                              },
                              "value": "_owner",
                              "raw": "\"_owner\""
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    },
                    "right": {
                      "type": "CallExpression",
                      "span": {
                        "start": 963,
                        "end": 986
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 963,
                          "end": 976
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 963,
                            "end": 967
                          },
                          "ctxt": 4,
                          "value": "keys",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 968,
                            "end": 976
                          },
                          "value": "includes"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "StringLiteral",
                            "span": {
                              "start": 977,
                              "end": 985
                            },
                            "value": "_store",
                            "raw": "\"_store\""
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  "right": {
                    "type": "CallExpression",
                    "span": {
                      "start": 996,
                      "end": 1018
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 996,
                        "end": 1009
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 996,
                          "end": 1000
                        },
                        "ctxt": 4,
                        "value": "keys",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 1001,
                          "end": 1009
                        },
                        "value": "includes"
                      }
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "StringLiteral",
                          "span": {
                            "start": 1010,
                            "end": 1017
                          },
                          "value": "props",
                          "raw": "\"props\""
                        }
                      }
                    ],
                    "typeArguments": null
                  }
                }
              }
            }
          ]
        },
        "generator": false,
        "async": false,
        "typeParameters": null,
        "returnType": null
      },
      {
        "type": "IfStatement",
        "span": {
          "start": 1032,
          "end": 1093
        },
        "test": {
          "type": "BinaryExpression",
          "span": {
            "start": 1036,
            "end": 1078
          },
          "operator": "||",
          "left": {
            "type": "BinaryExpression",
            "span": {
              "start": 1036,
              "end": 1049
            },
            "operator": "==",
            "left": {
              "type": "Identifier",
              "span": {
                "start": 1036,
                "end": 1041
              },
              "ctxt": 3,
              "value": "props",
              "optional": false
            },
            "right": {
              "type": "NullLiteral",
              "span": {
                "start": 1045,
                "end": 1049
              }
            }
          },
          "right": {
            "type": "BinaryExpression",
            "span": {
              "start": 1053,
              "end": 1078
            },
            "operator": "!==",
            "left": {
              "type": "UnaryExpression",
              "span": {
                "start": 1053,
                "end": 1065
              },
              "operator": "typeof",
              "argument": {
                "type": "Identifier",
                "span": {
                  "start": 1060,
                  "end": 1065
                },
                "ctxt": 3,
                "value": "props",
                "optional": false
              }
            },
            "right": {
              "type": "StringLiteral",
              "span": {
                "start": 1070,
                "end": 1078
              },
              "value": "object",
              "raw": "\"object\""
            }
          }
        },
        "consequent": {
          "type": "ReturnStatement",
          "span": {
            "start": 1080,
            "end": 1093
          },
          "argument": {
            "type": "Identifier",
            "span": {
              "start": 1087,
              "end": 1092
            },
            "ctxt": 3,
            "value": "props",
            "optional": false
          }
        },
        "alternate": null
      },
      {
        "type": "IfStatement",
        "span": {
          "start": 1097,
          "end": 1172
        },
        "test": {
          "type": "CallExpression",
          "span": {
            "start": 1101,
            "end": 1121
          },
          "ctxt": 0,
          "callee": {
            "type": "MemberExpression",
            "span": {
              "start": 1101,
              "end": 1114
            },
            "object": {
              "type": "Identifier",
              "span": {
                "start": 1101,
                "end": 1106
              },
              "ctxt": 1,
              "value": "Array",
              "optional": false
            },
            "property": {
              "type": "Identifier",
              "span": {
                "start": 1107,
                "end": 1114
              },
              "value": "isArray"
            }
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "Identifier",
                "span": {
                  "start": 1115,
                  "end": 1120
                },
                "ctxt": 3,
                "value": "props",
                "optional": false
              }
            }
          ],
          "typeArguments": null
        },
        "consequent": {
          "type": "BlockStatement",
          "span": {
            "start": 1123,
            "end": 1172
          },
          "ctxt": 5,
          "stmts": [
            {
              "type": "ReturnStatement",
              "span": {
                "start": 1129,
                "end": 1168
              },
              "argument": {
                "type": "CallExpression",
                "span": {
                  "start": 1136,
                  "end": 1167
                },
                "ctxt": 0,
                "callee": {
                  "type": "MemberExpression",
                  "span": {
                    "start": 1136,
                    "end": 1145
                  },
                  "object": {
                    "type": "Identifier",
                    "span": {
                      "start": 1136,
                      "end": 1141
                    },
                    "ctxt": 3,
                    "value": "props",
                    "optional": false
                  },
                  "property": {
                    "type": "Identifier",
                    "span": {
                      "start": 1142,
                      "end": 1145
                    },
                    "value": "map"
                  }
                },
                "arguments": [
                  {
                    "spread": null,
                    "expression": {
                      "type": "Identifier",
                      "span": {
                        "start": 1146,
                        "end": 1166
                      },
                      "ctxt": 2,
                      "value": "forketSerializeProps",
                      "optional": false
                    }
                  }
                ],
                "typeArguments": null
              }
            }
          ]
        },
        "alternate": null
      },
      {
        "type": "IfStatement",
        "span": {
          "start": 1175,
          "end": 1260
        },
        "test": {
          "type": "CallExpression",
          "span": {
            "start": 1179,
            "end": 1200
          },
          "ctxt": 0,
          "callee": {
            "type": "Identifier",
            "span": {
              "start": 1179,
              "end": 1193
            },
            "ctxt": 3,
            "value": "isValidElement",
            "optional": false
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "Identifier",
                "span": {
                  "start": 1194,
                  "end": 1199
                },
                "ctxt": 3,
                "value": "props",
                "optional": false
              }
            }
          ],
          "typeArguments": null
        },
        "consequent": {
          "type": "BlockStatement",
          "span": {
            "start": 1202,
            "end": 1260
          },
          "ctxt": 6,
          "stmts": [
            {
              "type": "ReturnStatement",
              "span": {
                "start": 1208,
                "end": 1221
              },
              "argument": {
                "type": "BooleanLiteral",
                "span": {
                  "start": 1215,
                  "end": 1220
                },
                "value": false
              }
            }
          ]
        },
        "alternate": null
      },
      {
        "type": "VariableDeclaration",
        "span": {
          "start": 1264,
          "end": 1286
        },
        "ctxt": 0,
        "kind": "const",
        "declare": false,
        "declarations": [
          {
            "type": "VariableDeclarator",
            "span": {
              "start": 1270,
              "end": 1285
            },
            "id": {
              "type": "Identifier",
              "span": {
                "start": 1270,
                "end": 1280
              },
              "ctxt": 3,
              "value": "serialized",
              "optional": false,
              "typeAnnotation": null
            },
            "init": {
              "type": "ObjectExpression",
              "span": {
                "start": 1283,
                "end": 1285
              },
              "properties": []
            },
            "definite": false
          }
        ]
      },
      {
        "type": "ForInStatement",
        "span": {
          "start": 1289,
          "end": 1603
        },
        "left": {
          "type": "VariableDeclaration",
          "span": {
            "start": 1294,
            "end": 1303
          },
          "ctxt": 0,
          "kind": "const",
          "declare": false,
          "declarations": [
            {
              "type": "VariableDeclarator",
              "span": {
                "start": 1300,
                "end": 1303
              },
              "id": {
                "type": "Identifier",
                "span": {
                  "start": 1300,
                  "end": 1303
                },
                "ctxt": 7,
                "value": "key",
                "optional": false,
                "typeAnnotation": null
              },
              "init": null,
              "definite": false
            }
          ]
        },
        "right": {
          "type": "Identifier",
          "span": {
            "start": 1307,
            "end": 1312
          },
          "ctxt": 3,
          "value": "props",
          "optional": false
        },
        "body": {
          "type": "BlockStatement",
          "span": {
            "start": 1314,
            "end": 1603
          },
          "ctxt": 8,
          "stmts": [
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 1320,
                "end": 1345
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 1326,
                    "end": 1344
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 1326,
                      "end": 1331
                    },
                    "ctxt": 8,
                    "value": "value",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1334,
                      "end": 1344
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1334,
                        "end": 1339
                      },
                      "ctxt": 3,
                      "value": "props",
                      "optional": false
                    },
                    "property": {
                      "type": "Computed",
                      "span": {
                        "start": 1339,
                        "end": 1344
                      },
                      "expression": {
                        "type": "Identifier",
                        "span": {
                          "start": 1340,
                          "end": 1343
                        },
                        "ctxt": 7,
                        "value": "key",
                        "optional": false
                      }
                    }
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1350,
                "end": 1448
              },
              "test": {
                "type": "BinaryExpression",
                "span": {
                  "start": 1354,
                  "end": 1381
                },
                "operator": "===",
                "left": {
                  "type": "UnaryExpression",
                  "span": {
                    "start": 1354,
                    "end": 1366
                  },
                  "operator": "typeof",
                  "argument": {
                    "type": "Identifier",
                    "span": {
                      "start": 1361,
                      "end": 1366
                    },
                    "ctxt": 8,
                    "value": "value",
                    "optional": false
                  }
                },
                "right": {
                  "type": "StringLiteral",
                  "span": {
                    "start": 1371,
                    "end": 1381
                  },
                  "value": "function",
                  "raw": "\"function\""
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1383,
                  "end": 1448
                },
                "ctxt": 9,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1391,
                      "end": 1426
                    },
                    "expression": {
                      "type": "AssignmentExpression",
                      "span": {
                        "start": 1391,
                        "end": 1425
                      },
                      "operator": "=",
                      "left": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1391,
                          "end": 1406
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1391,
                            "end": 1401
                          },
                          "ctxt": 3,
                          "value": "serialized",
                          "optional": false
                        },
                        "property": {
                          "type": "Computed",
                          "span": {
                            "start": 1401,
                            "end": 1406
                          },
                          "expression": {
                            "type": "Identifier",
                            "span": {
                              "start": 1402,
                              "end": 1405
                            },
                            "ctxt": 7,
                            "value": "key",
                            "optional": false
                          }
                        }
                      },
                      "right": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 1409,
                          "end": 1425
                        },
                        "value": "$FRSC_function",
                        "raw": "\"$FRSC_function\""
                      }
                    }
                  },
                  {
                    "type": "ContinueStatement",
                    "span": {
                      "start": 1433,
                      "end": 1442
                    },
                    "label": null
                  }
                ]
              },
              "alternate": null
            },
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 1453,
                "end": 1504
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 1459,
                    "end": 1503
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 1459,
                      "end": 1473
                    },
                    "ctxt": 8,
                    "value": "serializedProp",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "CallExpression",
                    "span": {
                      "start": 1476,
                      "end": 1503
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "Identifier",
                      "span": {
                        "start": 1476,
                        "end": 1496
                      },
                      "ctxt": 2,
                      "value": "forketSerializeProps",
                      "optional": false
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 1497,
                            "end": 1502
                          },
                          "ctxt": 8,
                          "value": "value",
                          "optional": false
                        }
                      }
                    ],
                    "typeArguments": null
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1509,
                "end": 1599
              },
              "test": {
                "type": "BinaryExpression",
                "span": {
                  "start": 1513,
                  "end": 1537
                },
                "operator": "!==",
                "left": {
                  "type": "Identifier",
                  "span": {
                    "start": 1513,
                    "end": 1527
                  },
                  "ctxt": 8,
                  "value": "serializedProp",
                  "optional": false
                },
                "right": {
                  "type": "BooleanLiteral",
                  "span": {
                    "start": 1532,
                    "end": 1537
                  },
                  "value": false
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1539,
                  "end": 1599
                },
                "ctxt": 10,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1547,
                      "end": 1593
                    },
                    "expression": {
                      "type": "AssignmentExpression",
                      "span": {
                        "start": 1547,
                        "end": 1592
                      },
                      "operator": "=",
                      "left": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1547,
                          "end": 1562
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1547,
                            "end": 1557
                          },
                          "ctxt": 3,
                          "value": "serialized",
                          "optional": false
                        },
                        "property": {
                          "type": "Computed",
                          "span": {
                            "start": 1557,
                            "end": 1562
                          },
                          "expression": {
                            "type": "Identifier",
                            "span": {
                              "start": 1558,
                              "end": 1561
                            },
                            "ctxt": 7,
                            "value": "key",
                            "optional": false
                          }
                        }
                      },
                      "right": {
                        "type": "CallExpression",
                        "span": {
                          "start": 1565,
                          "end": 1592
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "Identifier",
                          "span": {
                            "start": 1565,
                            "end": 1585
                          },
                          "ctxt": 2,
                          "value": "forketSerializeProps",
                          "optional": false
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "Identifier",
                              "span": {
                                "start": 1586,
                                "end": 1591
                              },
                              "ctxt": 8,
                              "value": "value",
                              "optional": false
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    }
                  }
                ]
              },
              "alternate": null
            }
          ]
        }
      },
      {
        "type": "ReturnStatement",
        "span": {
          "start": 1607,
          "end": 1625
        },
        "argument": {
          "type": "Identifier",
          "span": {
            "start": 1614,
            "end": 1624
          },
          "ctxt": 3,
          "value": "serialized",
          "optional": false
        }
      }
    ]
  },
  "generator": false,
  "async": false,
  "typeParameters": null,
  "returnType": null
}
}