/* This file is auto-generated by Forket. Don't change it manually. */

module.exports = function () {
  return {
  "type": "FunctionDeclaration",
  "identifier": {
    "type": "Identifier",
    "span": {
      "start": 714,
      "end": 729
    },
    "ctxt": 2,
    "value": "serialize$Props",
    "optional": false
  },
  "declare": false,
  "params": [
    {
      "type": "Parameter",
      "span": {
        "start": 730,
        "end": 735
      },
      "decorators": [],
      "pat": {
        "type": "Identifier",
        "span": {
          "start": 730,
          "end": 735
        },
        "ctxt": 3,
        "value": "props",
        "optional": false,
        "typeAnnotation": null
      }
    }
  ],
  "decorators": [],
  "span": {
    "start": 705,
    "end": 1521
  },
  "ctxt": 3,
  "body": {
    "type": "BlockStatement",
    "span": {
      "start": 737,
      "end": 1521
    },
    "ctxt": 3,
    "stmts": [
      {
        "type": "FunctionDeclaration",
        "identifier": {
          "type": "Identifier",
          "span": {
            "start": 750,
            "end": 764
          },
          "ctxt": 3,
          "value": "isValidElement",
          "optional": false
        },
        "declare": false,
        "params": [
          {
            "type": "Parameter",
            "span": {
              "start": 765,
              "end": 768
            },
            "decorators": [],
            "pat": {
              "type": "Identifier",
              "span": {
                "start": 765,
                "end": 768
              },
              "ctxt": 4,
              "value": "obj",
              "optional": false,
              "typeAnnotation": null
            }
          }
        ],
        "decorators": [],
        "span": {
          "start": 741,
          "end": 980
        },
        "ctxt": 4,
        "body": {
          "type": "BlockStatement",
          "span": {
            "start": 770,
            "end": 980
          },
          "ctxt": 4,
          "stmts": [
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 776,
                "end": 806
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 782,
                    "end": 805
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 782,
                      "end": 786
                    },
                    "ctxt": 4,
                    "value": "keys",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "CallExpression",
                    "span": {
                      "start": 789,
                      "end": 805
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 789,
                        "end": 800
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 789,
                          "end": 795
                        },
                        "ctxt": 1,
                        "value": "Object",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 796,
                          "end": 800
                        },
                        "value": "keys"
                      }
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 801,
                            "end": 804
                          },
                          "ctxt": 4,
                          "value": "obj",
                          "optional": false
                        }
                      }
                    ],
                    "typeArguments": null
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "ReturnStatement",
              "span": {
                "start": 811,
                "end": 976
              },
              "argument": {
                "type": "ParenthesisExpression",
                "span": {
                  "start": 818,
                  "end": 975
                },
                "expression": {
                  "type": "BinaryExpression",
                  "span": {
                    "start": 826,
                    "end": 969
                  },
                  "operator": "&&",
                  "left": {
                    "type": "BinaryExpression",
                    "span": {
                      "start": 826,
                      "end": 937
                    },
                    "operator": "&&",
                    "left": {
                      "type": "BinaryExpression",
                      "span": {
                        "start": 826,
                        "end": 904
                      },
                      "operator": "&&",
                      "left": {
                        "type": "BinaryExpression",
                        "span": {
                          "start": 826,
                          "end": 871
                        },
                        "operator": "&&",
                        "left": {
                          "type": "BinaryExpression",
                          "span": {
                            "start": 826,
                            "end": 849
                          },
                          "operator": "===",
                          "left": {
                            "type": "UnaryExpression",
                            "span": {
                              "start": 826,
                              "end": 836
                            },
                            "operator": "typeof",
                            "argument": {
                              "type": "Identifier",
                              "span": {
                                "start": 833,
                                "end": 836
                              },
                              "ctxt": 4,
                              "value": "obj",
                              "optional": false
                            }
                          },
                          "right": {
                            "type": "StringLiteral",
                            "span": {
                              "start": 841,
                              "end": 849
                            },
                            "value": "object",
                            "raw": "\"object\""
                          }
                        },
                        "right": {
                          "type": "BinaryExpression",
                          "span": {
                            "start": 859,
                            "end": 871
                          },
                          "operator": "!==",
                          "left": {
                            "type": "Identifier",
                            "span": {
                              "start": 859,
                              "end": 862
                            },
                            "ctxt": 4,
                            "value": "obj",
                            "optional": false
                          },
                          "right": {
                            "type": "NullLiteral",
                            "span": {
                              "start": 867,
                              "end": 871
                            }
                          }
                        }
                      },
                      "right": {
                        "type": "CallExpression",
                        "span": {
                          "start": 881,
                          "end": 904
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "MemberExpression",
                          "span": {
                            "start": 881,
                            "end": 894
                          },
                          "object": {
                            "type": "Identifier",
                            "span": {
                              "start": 881,
                              "end": 885
                            },
                            "ctxt": 4,
                            "value": "keys",
                            "optional": false
                          },
                          "property": {
                            "type": "Identifier",
                            "span": {
                              "start": 886,
                              "end": 894
                            },
                            "value": "includes"
                          }
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "StringLiteral",
                              "span": {
                                "start": 895,
                                "end": 903
                              },
                              "value": "_owner",
                              "raw": "\"_owner\""
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    },
                    "right": {
                      "type": "CallExpression",
                      "span": {
                        "start": 914,
                        "end": 937
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 914,
                          "end": 927
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 914,
                            "end": 918
                          },
                          "ctxt": 4,
                          "value": "keys",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 919,
                            "end": 927
                          },
                          "value": "includes"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "StringLiteral",
                            "span": {
                              "start": 928,
                              "end": 936
                            },
                            "value": "_store",
                            "raw": "\"_store\""
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  "right": {
                    "type": "CallExpression",
                    "span": {
                      "start": 947,
                      "end": 969
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 947,
                        "end": 960
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 947,
                          "end": 951
                        },
                        "ctxt": 4,
                        "value": "keys",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 952,
                          "end": 960
                        },
                        "value": "includes"
                      }
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "StringLiteral",
                          "span": {
                            "start": 961,
                            "end": 968
                          },
                          "value": "props",
                          "raw": "\"props\""
                        }
                      }
                    ],
                    "typeArguments": null
                  }
                }
              }
            }
          ]
        },
        "generator": false,
        "async": false,
        "typeParameters": null,
        "returnType": null
      },
      {
        "type": "IfStatement",
        "span": {
          "start": 983,
          "end": 1044
        },
        "test": {
          "type": "BinaryExpression",
          "span": {
            "start": 987,
            "end": 1029
          },
          "operator": "||",
          "left": {
            "type": "BinaryExpression",
            "span": {
              "start": 987,
              "end": 1000
            },
            "operator": "==",
            "left": {
              "type": "Identifier",
              "span": {
                "start": 987,
                "end": 992
              },
              "ctxt": 3,
              "value": "props",
              "optional": false
            },
            "right": {
              "type": "NullLiteral",
              "span": {
                "start": 996,
                "end": 1000
              }
            }
          },
          "right": {
            "type": "BinaryExpression",
            "span": {
              "start": 1004,
              "end": 1029
            },
            "operator": "!==",
            "left": {
              "type": "UnaryExpression",
              "span": {
                "start": 1004,
                "end": 1016
              },
              "operator": "typeof",
              "argument": {
                "type": "Identifier",
                "span": {
                  "start": 1011,
                  "end": 1016
                },
                "ctxt": 3,
                "value": "props",
                "optional": false
              }
            },
            "right": {
              "type": "StringLiteral",
              "span": {
                "start": 1021,
                "end": 1029
              },
              "value": "object",
              "raw": "\"object\""
            }
          }
        },
        "consequent": {
          "type": "ReturnStatement",
          "span": {
            "start": 1031,
            "end": 1044
          },
          "argument": {
            "type": "Identifier",
            "span": {
              "start": 1038,
              "end": 1043
            },
            "ctxt": 3,
            "value": "props",
            "optional": false
          }
        },
        "alternate": null
      },
      {
        "type": "IfStatement",
        "span": {
          "start": 1048,
          "end": 1118
        },
        "test": {
          "type": "CallExpression",
          "span": {
            "start": 1052,
            "end": 1072
          },
          "ctxt": 0,
          "callee": {
            "type": "MemberExpression",
            "span": {
              "start": 1052,
              "end": 1065
            },
            "object": {
              "type": "Identifier",
              "span": {
                "start": 1052,
                "end": 1057
              },
              "ctxt": 1,
              "value": "Array",
              "optional": false
            },
            "property": {
              "type": "Identifier",
              "span": {
                "start": 1058,
                "end": 1065
              },
              "value": "isArray"
            }
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "Identifier",
                "span": {
                  "start": 1066,
                  "end": 1071
                },
                "ctxt": 3,
                "value": "props",
                "optional": false
              }
            }
          ],
          "typeArguments": null
        },
        "consequent": {
          "type": "BlockStatement",
          "span": {
            "start": 1074,
            "end": 1118
          },
          "ctxt": 5,
          "stmts": [
            {
              "type": "ReturnStatement",
              "span": {
                "start": 1080,
                "end": 1114
              },
              "argument": {
                "type": "CallExpression",
                "span": {
                  "start": 1087,
                  "end": 1113
                },
                "ctxt": 0,
                "callee": {
                  "type": "MemberExpression",
                  "span": {
                    "start": 1087,
                    "end": 1096
                  },
                  "object": {
                    "type": "Identifier",
                    "span": {
                      "start": 1087,
                      "end": 1092
                    },
                    "ctxt": 3,
                    "value": "props",
                    "optional": false
                  },
                  "property": {
                    "type": "Identifier",
                    "span": {
                      "start": 1093,
                      "end": 1096
                    },
                    "value": "map"
                  }
                },
                "arguments": [
                  {
                    "spread": null,
                    "expression": {
                      "type": "Identifier",
                      "span": {
                        "start": 1097,
                        "end": 1112
                      },
                      "ctxt": 2,
                      "value": "serialize$Props",
                      "optional": false
                    }
                  }
                ],
                "typeArguments": null
              }
            }
          ]
        },
        "alternate": null
      },
      {
        "type": "IfStatement",
        "span": {
          "start": 1121,
          "end": 1206
        },
        "test": {
          "type": "CallExpression",
          "span": {
            "start": 1125,
            "end": 1146
          },
          "ctxt": 0,
          "callee": {
            "type": "Identifier",
            "span": {
              "start": 1125,
              "end": 1139
            },
            "ctxt": 3,
            "value": "isValidElement",
            "optional": false
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "Identifier",
                "span": {
                  "start": 1140,
                  "end": 1145
                },
                "ctxt": 3,
                "value": "props",
                "optional": false
              }
            }
          ],
          "typeArguments": null
        },
        "consequent": {
          "type": "BlockStatement",
          "span": {
            "start": 1148,
            "end": 1206
          },
          "ctxt": 6,
          "stmts": [
            {
              "type": "ReturnStatement",
              "span": {
                "start": 1154,
                "end": 1167
              },
              "argument": {
                "type": "BooleanLiteral",
                "span": {
                  "start": 1161,
                  "end": 1166
                },
                "value": false
              }
            }
          ]
        },
        "alternate": null
      },
      {
        "type": "VariableDeclaration",
        "span": {
          "start": 1210,
          "end": 1232
        },
        "ctxt": 0,
        "kind": "const",
        "declare": false,
        "declarations": [
          {
            "type": "VariableDeclarator",
            "span": {
              "start": 1216,
              "end": 1231
            },
            "id": {
              "type": "Identifier",
              "span": {
                "start": 1216,
                "end": 1226
              },
              "ctxt": 3,
              "value": "serialized",
              "optional": false,
              "typeAnnotation": null
            },
            "init": {
              "type": "ObjectExpression",
              "span": {
                "start": 1229,
                "end": 1231
              },
              "properties": []
            },
            "definite": false
          }
        ]
      },
      {
        "type": "ForInStatement",
        "span": {
          "start": 1235,
          "end": 1497
        },
        "left": {
          "type": "VariableDeclaration",
          "span": {
            "start": 1240,
            "end": 1249
          },
          "ctxt": 0,
          "kind": "const",
          "declare": false,
          "declarations": [
            {
              "type": "VariableDeclarator",
              "span": {
                "start": 1246,
                "end": 1249
              },
              "id": {
                "type": "Identifier",
                "span": {
                  "start": 1246,
                  "end": 1249
                },
                "ctxt": 7,
                "value": "key",
                "optional": false,
                "typeAnnotation": null
              },
              "init": null,
              "definite": false
            }
          ]
        },
        "right": {
          "type": "Identifier",
          "span": {
            "start": 1253,
            "end": 1258
          },
          "ctxt": 3,
          "value": "props",
          "optional": false
        },
        "body": {
          "type": "BlockStatement",
          "span": {
            "start": 1260,
            "end": 1497
          },
          "ctxt": 8,
          "stmts": [
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 1266,
                "end": 1291
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 1272,
                    "end": 1290
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 1272,
                      "end": 1277
                    },
                    "ctxt": 8,
                    "value": "value",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1280,
                      "end": 1290
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1280,
                        "end": 1285
                      },
                      "ctxt": 3,
                      "value": "props",
                      "optional": false
                    },
                    "property": {
                      "type": "Computed",
                      "span": {
                        "start": 1285,
                        "end": 1290
                      },
                      "expression": {
                        "type": "Identifier",
                        "span": {
                          "start": 1286,
                          "end": 1289
                        },
                        "ctxt": 7,
                        "value": "key",
                        "optional": false
                      }
                    }
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1296,
                "end": 1352
              },
              "test": {
                "type": "BinaryExpression",
                "span": {
                  "start": 1300,
                  "end": 1327
                },
                "operator": "===",
                "left": {
                  "type": "UnaryExpression",
                  "span": {
                    "start": 1300,
                    "end": 1312
                  },
                  "operator": "typeof",
                  "argument": {
                    "type": "Identifier",
                    "span": {
                      "start": 1307,
                      "end": 1312
                    },
                    "ctxt": 8,
                    "value": "value",
                    "optional": false
                  }
                },
                "right": {
                  "type": "StringLiteral",
                  "span": {
                    "start": 1317,
                    "end": 1327
                  },
                  "value": "function",
                  "raw": "\"function\""
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1329,
                  "end": 1352
                },
                "ctxt": 9,
                "stmts": [
                  {
                    "type": "ContinueStatement",
                    "span": {
                      "start": 1337,
                      "end": 1346
                    },
                    "label": null
                  }
                ]
              },
              "alternate": null
            },
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 1357,
                "end": 1403
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 1363,
                    "end": 1402
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 1363,
                      "end": 1377
                    },
                    "ctxt": 8,
                    "value": "serializedProp",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "CallExpression",
                    "span": {
                      "start": 1380,
                      "end": 1402
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "Identifier",
                      "span": {
                        "start": 1380,
                        "end": 1395
                      },
                      "ctxt": 2,
                      "value": "serialize$Props",
                      "optional": false
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 1396,
                            "end": 1401
                          },
                          "ctxt": 8,
                          "value": "value",
                          "optional": false
                        }
                      }
                    ],
                    "typeArguments": null
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1408,
                "end": 1493
              },
              "test": {
                "type": "BinaryExpression",
                "span": {
                  "start": 1412,
                  "end": 1436
                },
                "operator": "!==",
                "left": {
                  "type": "Identifier",
                  "span": {
                    "start": 1412,
                    "end": 1426
                  },
                  "ctxt": 8,
                  "value": "serializedProp",
                  "optional": false
                },
                "right": {
                  "type": "BooleanLiteral",
                  "span": {
                    "start": 1431,
                    "end": 1436
                  },
                  "value": false
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1438,
                  "end": 1493
                },
                "ctxt": 10,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1446,
                      "end": 1487
                    },
                    "expression": {
                      "type": "AssignmentExpression",
                      "span": {
                        "start": 1446,
                        "end": 1486
                      },
                      "operator": "=",
                      "left": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1446,
                          "end": 1461
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1446,
                            "end": 1456
                          },
                          "ctxt": 3,
                          "value": "serialized",
                          "optional": false
                        },
                        "property": {
                          "type": "Computed",
                          "span": {
                            "start": 1456,
                            "end": 1461
                          },
                          "expression": {
                            "type": "Identifier",
                            "span": {
                              "start": 1457,
                              "end": 1460
                            },
                            "ctxt": 7,
                            "value": "key",
                            "optional": false
                          }
                        }
                      },
                      "right": {
                        "type": "CallExpression",
                        "span": {
                          "start": 1464,
                          "end": 1486
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "Identifier",
                          "span": {
                            "start": 1464,
                            "end": 1479
                          },
                          "ctxt": 2,
                          "value": "serialize$Props",
                          "optional": false
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "Identifier",
                              "span": {
                                "start": 1480,
                                "end": 1485
                              },
                              "ctxt": 8,
                              "value": "value",
                              "optional": false
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    }
                  }
                ]
              },
              "alternate": null
            }
          ]
        }
      },
      {
        "type": "ReturnStatement",
        "span": {
          "start": 1501,
          "end": 1519
        },
        "argument": {
          "type": "Identifier",
          "span": {
            "start": 1508,
            "end": 1518
          },
          "ctxt": 3,
          "value": "serialized",
          "optional": false
        }
      }
    ]
  },
  "generator": false,
  "async": false,
  "typeParameters": null,
  "returnType": null
}
}