/* This file is auto-generated by Forket. Don't change it manually. */

export default function (what, where, asSomething) {
  return [
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 1,
      "end": 38
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 7,
          "end": 37
        },
        "id": {
          "type": "ObjectPattern",
          "span": {
            "start": 7,
            "end": 19
          },
          "properties": [
            {
              "type": "KeyValuePatternProperty",
              "key": {
                "type": "Identifier",
                "span": {
                  "start": 9,
                  "end": 12
                },
                "value": what
              },
              "value": {
                "type": "Identifier",
                "span": {
                  "start": 14,
                  "end": 17
                },
                "ctxt": 2,
                "value": asSomething,
                "optional": false,
                "typeAnnotation": null
              }
            }
          ],
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "CallExpression",
          "span": {
            "start": 22,
            "end": 37
          },
          "ctxt": 0,
          "callee": {
            "type": "Identifier",
            "span": {
              "start": 22,
              "end": 29
            },
            "ctxt": 1,
            "value": "require",
            "optional": false
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "StringLiteral",
                "span": {
                  "start": 30,
                  "end": 36
                },
                "value": where,
                "raw": "\"" + where + "\""
              }
            }
          ],
          "typeArguments": null
        },
        "definite": false
      }
    ]
  }
]
}