/* This file is auto-generated by Forket. Don't change it manually. */

export default function (what, where) {
  return [
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 1628,
      "end": 1659
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 1634,
          "end": 1658
        },
        "id": {
          "type": "Identifier",
          "span": {
            "start": 1634,
            "end": 1639
          },
          "ctxt": 2,
          "value": what,
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "CallExpression",
          "span": {
            "start": 1642,
            "end": 1658
          },
          "ctxt": 0,
          "callee": {
            "type": "Identifier",
            "span": {
              "start": 1642,
              "end": 1649
            },
            "ctxt": 1,
            "value": "require",
            "optional": false
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "StringLiteral",
                "span": {
                  "start": 1650,
                  "end": 1657
                },
                "value": where,
                "raw": "\"" + where + "\""
              }
            }
          ],
          "typeArguments": null
        },
        "definite": false
      }
    ]
  }
]
}