/* This file is auto-generated by Forket. Don't change it manually. */

export default function (id, funcName) {
  return [
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 1,
      "end": 88
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 7,
          "end": 88
        },
        "id": {
          "type": "Identifier",
          "span": {
            "start": 7,
            "end": 13
          },
          "ctxt": 2,
          "value": funcName,
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "FunctionExpression",
          "identifier": null,
          "params": [
            {
              "type": "Parameter",
              "span": {
                "start": 25,
                "end": 32
              },
              "decorators": [],
              "pat": {
                "type": "RestElement",
                "span": {
                  "start": 25,
                  "end": 32
                },
                "rest": {
                  "start": 25,
                  "end": 28
                },
                "argument": {
                  "type": "Identifier",
                  "span": {
                    "start": 28,
                    "end": 32
                  },
                  "ctxt": 3,
                  "value": "args",
                  "optional": false,
                  "typeAnnotation": null
                },
                "typeAnnotation": null
              }
            }
          ],
          "decorators": [],
          "span": {
            "start": 16,
            "end": 88
          },
          "ctxt": 3,
          "body": {
            "type": "BlockStatement",
            "span": {
              "start": 34,
              "end": 88
            },
            "ctxt": 3,
            "stmts": [
              {
                "type": "ReturnStatement",
                "span": {
                  "start": 38,
                  "end": 86
                },
                "argument": {
                  "type": "CallExpression",
                  "span": {
                    "start": 45,
                    "end": 85
                  },
                  "ctxt": 0,
                  "callee": {
                    "type": "CallExpression",
                    "span": {
                      "start": 45,
                      "end": 76
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 45,
                        "end": 60
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 45,
                          "end": 51
                        },
                        "ctxt": 1,
                        "value": "window",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 52,
                          "end": 60
                        },
                        "value": "FSA_call"
                      }
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "StringLiteral",
                          "span": {
                            "start": 61,
                            "end": 65
                          },
                          "value": id,
                          "raw": "\"" + id + "\""
                        }
                      },
                      {
                        "spread": null,
                        "expression": {
                          "type": "StringLiteral",
                          "span": {
                            "start": 67,
                            "end": 75
                          },
                          "value": funcName,
                          "raw": "\"" + funcName + "\""
                        }
                      }
                    ],
                    "typeArguments": null
                  },
                  "arguments": [
                    {
                      "spread": {
                        "start": 77,
                        "end": 80
                      },
                      "expression": {
                        "type": "Identifier",
                        "span": {
                          "start": 80,
                          "end": 84
                        },
                        "ctxt": 3,
                        "value": "args",
                        "optional": false
                      }
                    }
                  ],
                  "typeArguments": null
                }
              }
            ]
          },
          "generator": false,
          "async": false,
          "typeParameters": null,
          "returnType": null
        },
        "definite": false
      }
    ]
  }
]
}