/* This file is auto-generated by Forket. Don't change it manually. */

export default function (id, funcName) {
  return [
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 1043,
      "end": 1090
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 1049,
          "end": 1089
        },
        "id": {
          "type": "Identifier",
          "span": {
            "start": 1049,
            "end": 1055
          },
          "ctxt": 2,
          "value": funcName,
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "CallExpression",
          "span": {
            "start": 1058,
            "end": 1089
          },
          "ctxt": 0,
          "callee": {
            "type": "MemberExpression",
            "span": {
              "start": 1058,
              "end": 1073
            },
            "object": {
              "type": "Identifier",
              "span": {
                "start": 1058,
                "end": 1064
              },
              "ctxt": 1,
              "value": "window",
              "optional": false
            },
            "property": {
              "type": "Identifier",
              "span": {
                "start": 1065,
                "end": 1073
              },
              "value": "FSA_call"
            }
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "StringLiteral",
                "span": {
                  "start": 1074,
                  "end": 1078
                },
                "value": id,
                "raw": "\"" + id + "\""
              }
            },
            {
              "spread": null,
              "expression": {
                "type": "StringLiteral",
                "span": {
                  "start": 1080,
                  "end": 1088
                },
                "value": funcName,
                "raw": "\"" + funcName + "\""
              }
            }
          ],
          "typeArguments": null
        },
        "definite": false
      }
    ]
  }
]
}