/* This file is auto-generated by Forket. Don't change it manually. */

export default function (id, funcName) {
  return [
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 866,
      "end": 953
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 872,
          "end": 953
        },
        "id": {
          "type": "Identifier",
          "span": {
            "start": 872,
            "end": 878
          },
          "ctxt": 2,
          "value": funcName,
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "FunctionExpression",
          "identifier": null,
          "params": [
            {
              "type": "Parameter",
              "span": {
                "start": 890,
                "end": 897
              },
              "decorators": [],
              "pat": {
                "type": "RestElement",
                "span": {
                  "start": 890,
                  "end": 897
                },
                "rest": {
                  "start": 890,
                  "end": 893
                },
                "argument": {
                  "type": "Identifier",
                  "span": {
                    "start": 893,
                    "end": 897
                  },
                  "ctxt": 3,
                  "value": "args",
                  "optional": false,
                  "typeAnnotation": null
                },
                "typeAnnotation": null
              }
            }
          ],
          "decorators": [],
          "span": {
            "start": 881,
            "end": 953
          },
          "ctxt": 3,
          "body": {
            "type": "BlockStatement",
            "span": {
              "start": 899,
              "end": 953
            },
            "ctxt": 3,
            "stmts": [
              {
                "type": "ReturnStatement",
                "span": {
                  "start": 903,
                  "end": 951
                },
                "argument": {
                  "type": "CallExpression",
                  "span": {
                    "start": 910,
                    "end": 950
                  },
                  "ctxt": 0,
                  "callee": {
                    "type": "CallExpression",
                    "span": {
                      "start": 910,
                      "end": 941
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 910,
                        "end": 925
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 910,
                          "end": 916
                        },
                        "ctxt": 1,
                        "value": "window",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 917,
                          "end": 925
                        },
                        "value": "FSA_call"
                      }
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "StringLiteral",
                          "span": {
                            "start": 926,
                            "end": 930
                          },
                          "value": id,
                          "raw": "\"" + id + "\""
                        }
                      },
                      {
                        "spread": null,
                        "expression": {
                          "type": "StringLiteral",
                          "span": {
                            "start": 932,
                            "end": 940
                          },
                          "value": funcName,
                          "raw": "\"" + funcName + "\""
                        }
                      }
                    ],
                    "typeArguments": null
                  },
                  "arguments": [
                    {
                      "spread": {
                        "start": 942,
                        "end": 945
                      },
                      "expression": {
                        "type": "Identifier",
                        "span": {
                          "start": 945,
                          "end": 949
                        },
                        "ctxt": 3,
                        "value": "args",
                        "optional": false
                      }
                    }
                  ],
                  "typeArguments": null
                }
              }
            ]
          },
          "generator": false,
          "async": false,
          "typeParameters": null,
          "returnType": null
        },
        "definite": false
      }
    ]
  }
]
}