/* This file is auto-generated by Forket. Don't change it manually. */

module.exports = function () {
  return [
  {
    "type": "ImportDeclaration",
    "span": {
      "start": 833,
      "end": 859
    },
    "specifiers": [
      {
        "type": "ImportDefaultSpecifier",
        "span": {
          "start": 840,
          "end": 845
        },
        "local": {
          "type": "Identifier",
          "span": {
            "start": 840,
            "end": 845
          },
          "ctxt": 2,
          "value": "React",
          "optional": false
        }
      }
    ],
    "source": {
      "type": "StringLiteral",
      "span": {
        "start": 851,
        "end": 858
      },
      "value": "react",
      "raw": "\"react\""
    },
    "typeOnly": false,
    "with": null,
    "phase": "evaluation"
  },
  {
    "type": "ImportDeclaration",
    "span": {
      "start": 860,
      "end": 906
    },
    "specifiers": [
      {
        "type": "ImportDefaultSpecifier",
        "span": {
          "start": 867,
          "end": 881
        },
        "local": {
          "type": "Identifier",
          "span": {
            "start": 867,
            "end": 881
          },
          "ctxt": 2,
          "value": "ReactDOMClient",
          "optional": false
        }
      }
    ],
    "source": {
      "type": "StringLiteral",
      "span": {
        "start": 887,
        "end": 905
      },
      "value": "react-dom/client",
      "raw": "\"react-dom/client\""
    },
    "typeOnly": false,
    "with": null,
    "phase": "evaluation"
  }
]
}