import path from 'path';
import fs from 'fs';
import swc from '@swc/core';
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TOP_COMMENT = "/* This file is auto-generated by Forket. Don't change it manually. */\n\n";
const FILES = [
  {
    codeFile: path.join(__dirname, "clientBoundaryWrapper", "/code.js"),
    generator: function (ast) {
      let json = JSON.stringify(ast.body[0], null, 2);
      json = json.replace(/"\ComponentName"/g, 'componentName + "Boundary"');
      json = json.replace(/"value": "ProductsList"/g, '"value": componentName');
      json = json.replace(/"f_1"/g, "id");
      json = json.replace(/\\"f_1\\"/g, '\\"" + id + "\\"');
      json = json.replace(/\\"ProductsList\\"/g, '\\"" + componentName + "\\"');
      return `export default function (id, componentName) {
  return ${json}
}`;
    }
  },
  {
    codeFile: path.join(__dirname, "importCommonJS", "/code.js"),
    generator: function (ast) {
      let json = JSON.stringify(ast.body, null, 2);
      json = json.replace(/"React"/g, "what");
      json = json.replace(/"react"/g, "where");
      json = json.replace(/\\"react\\"/g, '\\"" + where + "\\"');
      return `export default function (what, where) {
  return ${json}
}`;
    }
  },
  {
    codeFile: path.join(__dirname, "importCommonJSDestruct", "/code.js"),
    generator: function (ast) {
      let json = JSON.stringify(ast.body, null, 2);
      json = json.replace(/"React"/g, "what");
      json = json.replace(/"react"/g, "where");
      json = json.replace(/\\"react\\"/g, '\\"" + where + "\\"');
      return `export default function (what, where) {
  return ${json}
}`;
    }
  },
  {
    codeFile: path.join(__dirname, "clientSideServerActionCall", "/code.js"),
    generator: function (ast) {
      let json = JSON.stringify(ast.body, null, 2);
      json = json.replace(/"FooBar"/g, "funcName");
      json = json.replace(/\\"FooBar\\"/g, '\\"" + funcName + "\\"');
      json = json.replace(/"ID"/g, "id");
      json = json.replace(/\\"ID\\"/g, '\\"" + id + "\\"');
      return `export default function (id, funcName) {
  return ${json}
}`;
    }
  },
  {
    codeFile: path.join(__dirname, "importESM", "/code.js"),
    generator: function (ast) {
      let json = JSON.stringify(ast.body, null, 2);
      json = json.replace(/"React"/g, "what");
      json = json.replace(/"react"/g, "where");
      json = json.replace(/\\"react\\"/g, '\\"" + where + "\\"');
      json = json.replace(/"ImportDefaultSpecifier"/g, "specifier");
      return `export default function (what, where, specifier = "ImportDefaultSpecifier") {
  return ${json}
}`;
    }
  },
  {
    codeFile: path.join(__dirname, "exposeGlobal", "/code.js"),
    generator: function (ast) {
      let json = JSON.stringify(ast.body, null, 2);
      json = json.replace(/"Foo"/g, "windowKey");
      json = json.replace(/"Bar"/g, "value");
      return `export default function (windowKey, value) {
  return ${json}
}`;
    }
  },
  {
    codeFile: path.join(__dirname, "initClientCode", "/code.js"),
    generator: function (ast) {
      let json = JSON.stringify(ast.body, null, 2);
      return `export default function () {
  return ${json}
}`;
    }
  },
  {
    codeFile: path.join(__dirname, "createMap", "/code.js"),
    generator: function (ast) {
      ast.body[0].declarations[0].init.properties = 1111;
      let json = JSON.stringify(ast.body, null, 2);
      json = json.replace(/"mapName"/g, "variableName");
      json = json.replace(
        "1111",
        `values.map(v => {
          return {
            "type": "KeyValueProperty",
            "key": {
              "type": "Identifier",
              "span": {
                "start": 884,
                "end": 888
              },
              "value": v[0]
            },
            "value": {
              "type": "Identifier",
              "span": {
                "start": 890,
                "end": 899
              },
              "ctxt": 1,
              "value": v[1],
              "optional": false
            }
          };
        })`
      );
      return `export default function (variableName, values) {
  return ${json}
}`;
    }
  },
  {
    codeFile: path.join(__dirname, "serverActionsHandler", "/code.js"),
    generator: function (ast) {
      let json = JSON.stringify(ast, null, 2);
      return `export default function () {
  return ${json}
}`;
    }
  }
];


(async function() {
  FILES.forEach(async file => {
    const code = fs.readFileSync(file.codeFile, "utf8");
    const dir = path.dirname(file.codeFile);
    const { parse } = swc;
    const ast = await parse(code, {
      syntax: "typescript",
      tsx: true,
      decorators: false
    });
    fs.writeFileSync(path.join(dir, 'ast.json'), JSON.stringify(ast, null, 2));
    fs.writeFileSync(path.join(dir, "index.js"), TOP_COMMENT + file.generator(ast));
  });
})();