/* This file is auto-generated by Forket. Don't change it manually. */

export default function (what, where, asSomething) {
  return [
  {
    "type": "ImportDeclaration",
    "span": {
      "start": 982,
      "end": 1017
    },
    "specifiers": [
      {
        "type": "ImportSpecifier",
        "span": {
          "start": 991,
          "end": 1001
        },
        "local": {
          "type": "Identifier",
          "span": {
            "start": 998,
            "end": 1001
          },
          "ctxt": 2,
          "value": asSomething,
          "optional": false
        },
        "imported": {
          "type": "Identifier",
          "span": {
            "start": 991,
            "end": 994
          },
          "ctxt": 0,
          "value": what,
          "optional": false
        },
        "isTypeOnly": false
      }
    ],
    "source": {
      "type": "StringLiteral",
      "span": {
        "start": 1009,
        "end": 1016
      },
      "value": where,
      "raw": "\"" + where + "\""
    },
    "typeOnly": false,
    "with": null,
    "phase": "evaluation"
  }
]
}