/* This file is auto-generated by Forket. Don't change it manually. */

export default function () {
  return {
  "type": "Module",
  "span": {
    "start": 922,
    "end": 1766
  },
  "body": [
    {
      "type": "ExportDefaultDeclaration",
      "span": {
        "start": 922,
        "end": 1766
      },
      "decl": {
        "type": "FunctionExpression",
        "identifier": {
          "type": "Identifier",
          "span": {
            "start": 952,
            "end": 971
          },
          "ctxt": 2,
          "value": "forketServerActions",
          "optional": false
        },
        "params": [
          {
            "type": "Parameter",
            "span": {
              "start": 972,
              "end": 975
            },
            "decorators": [],
            "pat": {
              "type": "Identifier",
              "span": {
                "start": 972,
                "end": 975
              },
              "ctxt": 3,
              "value": "req",
              "optional": false,
              "typeAnnotation": null
            }
          },
          {
            "type": "Parameter",
            "span": {
              "start": 977,
              "end": 980
            },
            "decorators": [],
            "pat": {
              "type": "Identifier",
              "span": {
                "start": 977,
                "end": 980
              },
              "ctxt": 3,
              "value": "res",
              "optional": false,
              "typeAnnotation": null
            }
          }
        ],
        "decorators": [],
        "span": {
          "start": 937,
          "end": 1766
        },
        "ctxt": 3,
        "body": {
          "type": "BlockStatement",
          "span": {
            "start": 982,
            "end": 1766
          },
          "ctxt": 3,
          "stmts": [
            {
              "type": "ExpressionStatement",
              "span": {
                "start": 986,
                "end": 1036
              },
              "expression": {
                "type": "CallExpression",
                "span": {
                  "start": 986,
                  "end": 1035
                },
                "ctxt": 0,
                "callee": {
                  "type": "MemberExpression",
                  "span": {
                    "start": 986,
                    "end": 999
                  },
                  "object": {
                    "type": "Identifier",
                    "span": {
                      "start": 986,
                      "end": 989
                    },
                    "ctxt": 3,
                    "value": "res",
                    "optional": false
                  },
                  "property": {
                    "type": "Identifier",
                    "span": {
                      "start": 990,
                      "end": 999
                    },
                    "value": "setHeader"
                  }
                },
                "arguments": [
                  {
                    "spread": null,
                    "expression": {
                      "type": "StringLiteral",
                      "span": {
                        "start": 1000,
                        "end": 1014
                      },
                      "value": "Content-Type",
                      "raw": "\"Content-Type\""
                    }
                  },
                  {
                    "spread": null,
                    "expression": {
                      "type": "StringLiteral",
                      "span": {
                        "start": 1016,
                        "end": 1034
                      },
                      "value": "application/json",
                      "raw": "\"application/json\""
                    }
                  }
                ],
                "typeArguments": null
              }
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1039,
                "end": 1211
              },
              "test": {
                "type": "BinaryExpression",
                "span": {
                  "start": 1043,
                  "end": 1066
                },
                "operator": "&&",
                "left": {
                  "type": "UnaryExpression",
                  "span": {
                    "start": 1043,
                    "end": 1052
                  },
                  "operator": "!",
                  "argument": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1044,
                      "end": 1052
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1044,
                        "end": 1047
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1048,
                        "end": 1052
                      },
                      "value": "body"
                    }
                  }
                },
                "right": {
                  "type": "UnaryExpression",
                  "span": {
                    "start": 1056,
                    "end": 1066
                  },
                  "operator": "!",
                  "argument": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1057,
                      "end": 1066
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1057,
                        "end": 1060
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1061,
                        "end": 1066
                      },
                      "value": "files"
                    }
                  }
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1068,
                  "end": 1211
                },
                "ctxt": 4,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1074,
                      "end": 1138
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1074,
                        "end": 1137
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1074,
                          "end": 1086
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1074,
                            "end": 1081
                          },
                          "ctxt": 1,
                          "value": "console",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1082,
                            "end": 1086
                          },
                          "value": "warn"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "TemplateLiteral",
                            "span": {
                              "start": 1087,
                              "end": 1136
                            },
                            "expressions": [],
                            "quasis": [
                              {
                                "type": "TemplateElement",
                                "span": {
                                  "start": 1088,
                                  "end": 1135
                                },
                                "tail": true,
                                "cooked": "‎𐂐 Forket: the request object has no body.",
                                "raw": "‎𐂐 Forket: the request object has no body."
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1143,
                      "end": 1195
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1143,
                        "end": 1194
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1143,
                          "end": 1163
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1143,
                            "end": 1158
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1143,
                              "end": 1153
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1143,
                                "end": 1146
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1147,
                                "end": 1153
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1154,
                                  "end": 1157
                                },
                                "value": 400,
                                "raw": "400"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1159,
                            "end": 1163
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1164,
                              "end": 1193
                            },
                            "properties": [
                              {
                                "type": "KeyValueProperty",
                                "key": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1166,
                                    "end": 1171
                                  },
                                  "value": "error"
                                },
                                "value": {
                                  "type": "StringLiteral",
                                  "span": {
                                    "start": 1173,
                                    "end": 1191
                                  },
                                  "value": "No body provided",
                                  "raw": "\"No body provided\""
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ReturnStatement",
                    "span": {
                      "start": 1200,
                      "end": 1207
                    },
                    "argument": null
                  }
                ]
              },
              "alternate": null
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1214,
                "end": 1384
              },
              "test": {
                "type": "UnaryExpression",
                "span": {
                  "start": 1218,
                  "end": 1238
                },
                "operator": "!",
                "argument": {
                  "type": "MemberExpression",
                  "span": {
                    "start": 1219,
                    "end": 1238
                  },
                  "object": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1219,
                      "end": 1227
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1219,
                        "end": 1222
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1223,
                        "end": 1227
                      },
                      "value": "body"
                    }
                  },
                  "property": {
                    "type": "Identifier",
                    "span": {
                      "start": 1228,
                      "end": 1238
                    },
                    "value": "__actionId"
                  }
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1240,
                  "end": 1384
                },
                "ctxt": 5,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1246,
                      "end": 1313
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1246,
                        "end": 1312
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1246,
                          "end": 1258
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1246,
                            "end": 1253
                          },
                          "ctxt": 1,
                          "value": "console",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1254,
                            "end": 1258
                          },
                          "value": "warn"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "TemplateLiteral",
                            "span": {
                              "start": 1259,
                              "end": 1311
                            },
                            "expressions": [],
                            "quasis": [
                              {
                                "type": "TemplateElement",
                                "span": {
                                  "start": 1260,
                                  "end": 1310
                                },
                                "tail": true,
                                "cooked": "‎𐂐 Forket: the request object body has no id.",
                                "raw": "‎𐂐 Forket: the request object body has no id."
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1318,
                      "end": 1368
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1318,
                        "end": 1367
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1318,
                          "end": 1338
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1318,
                            "end": 1333
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1318,
                              "end": 1328
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1318,
                                "end": 1321
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1322,
                                "end": 1328
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1329,
                                  "end": 1332
                                },
                                "value": 400,
                                "raw": "400"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1334,
                            "end": 1338
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1339,
                              "end": 1366
                            },
                            "properties": [
                              {
                                "type": "KeyValueProperty",
                                "key": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1341,
                                    "end": 1346
                                  },
                                  "value": "error"
                                },
                                "value": {
                                  "type": "StringLiteral",
                                  "span": {
                                    "start": 1348,
                                    "end": 1364
                                  },
                                  "value": "No id provided",
                                  "raw": "\"No id provided\""
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ReturnStatement",
                    "span": {
                      "start": 1373,
                      "end": 1380
                    },
                    "argument": null
                  }
                ]
              },
              "alternate": null
            },
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 1387,
                "end": 1418
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 1393,
                    "end": 1417
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 1393,
                      "end": 1395
                    },
                    "ctxt": 3,
                    "value": "id",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1398,
                      "end": 1417
                    },
                    "object": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 1398,
                        "end": 1406
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 1398,
                          "end": 1401
                        },
                        "ctxt": 3,
                        "value": "req",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 1402,
                          "end": 1406
                        },
                        "value": "body"
                      }
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1407,
                        "end": 1417
                      },
                      "value": "__actionId"
                    }
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "TryStatement",
              "span": {
                "start": 1421,
                "end": 1764
              },
              "block": {
                "type": "BlockStatement",
                "span": {
                  "start": 1425,
                  "end": 1584
                },
                "ctxt": 6,
                "stmts": [
                  {
                    "type": "VariableDeclaration",
                    "span": {
                      "start": 1431,
                      "end": 1479
                    },
                    "ctxt": 0,
                    "kind": "const",
                    "declare": false,
                    "declarations": [
                      {
                        "type": "VariableDeclarator",
                        "span": {
                          "start": 1437,
                          "end": 1478
                        },
                        "id": {
                          "type": "Identifier",
                          "span": {
                            "start": 1437,
                            "end": 1444
                          },
                          "ctxt": 6,
                          "value": "context",
                          "optional": false,
                          "typeAnnotation": null
                        },
                        "init": {
                          "type": "ObjectExpression",
                          "span": {
                            "start": 1447,
                            "end": 1478
                          },
                          "properties": [
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1449,
                                  "end": 1456
                                },
                                "value": "request"
                              },
                              "value": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1458,
                                  "end": 1461
                                },
                                "ctxt": 3,
                                "value": "req",
                                "optional": false
                              }
                            },
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1463,
                                  "end": 1471
                                },
                                "value": "response"
                              },
                              "value": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1473,
                                  "end": 1476
                                },
                                "ctxt": 3,
                                "value": "res",
                                "optional": false
                              }
                            }
                          ]
                        },
                        "definite": false
                      }
                    ]
                  },
                  {
                    "type": "VariableDeclaration",
                    "span": {
                      "start": 1484,
                      "end": 1542
                    },
                    "ctxt": 0,
                    "kind": "const",
                    "declare": false,
                    "declarations": [
                      {
                        "type": "VariableDeclarator",
                        "span": {
                          "start": 1490,
                          "end": 1541
                        },
                        "id": {
                          "type": "Identifier",
                          "span": {
                            "start": 1490,
                            "end": 1496
                          },
                          "ctxt": 6,
                          "value": "result",
                          "optional": false,
                          "typeAnnotation": null
                        },
                        "init": {
                          "type": "AwaitExpression",
                          "span": {
                            "start": 1499,
                            "end": 1541
                          },
                          "argument": {
                            "type": "CallExpression",
                            "span": {
                              "start": 1505,
                              "end": 1541
                            },
                            "ctxt": 0,
                            "callee": {
                              "type": "MemberExpression",
                              "span": {
                                "start": 1505,
                                "end": 1516
                              },
                              "object": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1505,
                                  "end": 1512
                                },
                                "ctxt": 1,
                                "value": "actions",
                                "optional": false
                              },
                              "property": {
                                "type": "Computed",
                                "span": {
                                  "start": 1512,
                                  "end": 1516
                                },
                                "expression": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1513,
                                    "end": 1515
                                  },
                                  "ctxt": 3,
                                  "value": "id",
                                  "optional": false
                                }
                              }
                            },
                            "arguments": [
                              {
                                "spread": null,
                                "expression": {
                                  "type": "BinaryExpression",
                                  "span": {
                                    "start": 1517,
                                    "end": 1531
                                  },
                                  "operator": "||",
                                  "left": {
                                    "type": "MemberExpression",
                                    "span": {
                                      "start": 1517,
                                      "end": 1525
                                    },
                                    "object": {
                                      "type": "Identifier",
                                      "span": {
                                        "start": 1517,
                                        "end": 1520
                                      },
                                      "ctxt": 3,
                                      "value": "req",
                                      "optional": false
                                    },
                                    "property": {
                                      "type": "Identifier",
                                      "span": {
                                        "start": 1521,
                                        "end": 1525
                                      },
                                      "value": "body"
                                    }
                                  },
                                  "right": {
                                    "type": "ObjectExpression",
                                    "span": {
                                      "start": 1529,
                                      "end": 1531
                                    },
                                    "properties": []
                                  }
                                }
                              },
                              {
                                "spread": null,
                                "expression": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1533,
                                    "end": 1540
                                  },
                                  "ctxt": 6,
                                  "value": "context",
                                  "optional": false
                                }
                              }
                            ],
                            "typeArguments": null
                          }
                        },
                        "definite": false
                      }
                    ]
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1547,
                      "end": 1580
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1547,
                        "end": 1579
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1547,
                          "end": 1567
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1547,
                            "end": 1562
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1547,
                              "end": 1557
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1547,
                                "end": 1550
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1551,
                                "end": 1557
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1558,
                                  "end": 1561
                                },
                                "value": 200,
                                "raw": "200"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1563,
                            "end": 1567
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1568,
                              "end": 1578
                            },
                            "properties": [
                              {
                                "type": "Identifier",
                                "span": {
                                  "start": 1570,
                                  "end": 1576
                                },
                                "ctxt": 6,
                                "value": "result",
                                "optional": false
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  }
                ]
              },
              "handler": {
                "type": "CatchClause",
                "span": {
                  "start": 1585,
                  "end": 1764
                },
                "param": {
                  "type": "Identifier",
                  "span": {
                    "start": 1591,
                    "end": 1596
                  },
                  "ctxt": 7,
                  "value": "error",
                  "optional": false,
                  "typeAnnotation": null
                },
                "body": {
                  "type": "BlockStatement",
                  "span": {
                    "start": 1598,
                    "end": 1764
                  },
                  "ctxt": 7,
                  "stmts": [
                    {
                      "type": "ExpressionStatement",
                      "span": {
                        "start": 1604,
                        "end": 1674
                      },
                      "expression": {
                        "type": "CallExpression",
                        "span": {
                          "start": 1604,
                          "end": 1673
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "MemberExpression",
                          "span": {
                            "start": 1604,
                            "end": 1617
                          },
                          "object": {
                            "type": "Identifier",
                            "span": {
                              "start": 1604,
                              "end": 1611
                            },
                            "ctxt": 1,
                            "value": "console",
                            "optional": false
                          },
                          "property": {
                            "type": "Identifier",
                            "span": {
                              "start": 1612,
                              "end": 1617
                            },
                            "value": "error"
                          }
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "TemplateLiteral",
                              "span": {
                                "start": 1618,
                                "end": 1665
                              },
                              "expressions": [
                                {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1660,
                                    "end": 1662
                                  },
                                  "ctxt": 3,
                                  "value": "id",
                                  "optional": false
                                }
                              ],
                              "quasis": [
                                {
                                  "type": "TemplateElement",
                                  "span": {
                                    "start": 1619,
                                    "end": 1658
                                  },
                                  "tail": false,
                                  "cooked": "‎𐂐 Forket: error in server action ",
                                  "raw": "‎𐂐 Forket: error in server action "
                                },
                                {
                                  "type": "TemplateElement",
                                  "span": {
                                    "start": 1663,
                                    "end": 1664
                                  },
                                  "tail": true,
                                  "cooked": ":",
                                  "raw": ":"
                                }
                              ]
                            }
                          },
                          {
                            "spread": null,
                            "expression": {
                              "type": "Identifier",
                              "span": {
                                "start": 1667,
                                "end": 1672
                              },
                              "ctxt": 7,
                              "value": "error",
                              "optional": false
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    },
                    {
                      "type": "ExpressionStatement",
                      "span": {
                        "start": 1679,
                        "end": 1760
                      },
                      "expression": {
                        "type": "CallExpression",
                        "span": {
                          "start": 1679,
                          "end": 1759
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "MemberExpression",
                          "span": {
                            "start": 1679,
                            "end": 1699
                          },
                          "object": {
                            "type": "CallExpression",
                            "span": {
                              "start": 1679,
                              "end": 1694
                            },
                            "ctxt": 0,
                            "callee": {
                              "type": "MemberExpression",
                              "span": {
                                "start": 1679,
                                "end": 1689
                              },
                              "object": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1679,
                                  "end": 1682
                                },
                                "ctxt": 3,
                                "value": "res",
                                "optional": false
                              },
                              "property": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1683,
                                  "end": 1689
                                },
                                "value": "status"
                              }
                            },
                            "arguments": [
                              {
                                "spread": null,
                                "expression": {
                                  "type": "NumericLiteral",
                                  "span": {
                                    "start": 1690,
                                    "end": 1693
                                  },
                                  "value": 200,
                                  "raw": "200"
                                }
                              }
                            ],
                            "typeArguments": null
                          },
                          "property": {
                            "type": "Identifier",
                            "span": {
                              "start": 1695,
                              "end": 1699
                            },
                            "value": "json"
                          }
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "ObjectExpression",
                              "span": {
                                "start": 1700,
                                "end": 1758
                              },
                              "properties": [
                                {
                                  "type": "KeyValueProperty",
                                  "key": {
                                    "type": "Identifier",
                                    "span": {
                                      "start": 1702,
                                      "end": 1707
                                    },
                                    "value": "error"
                                  },
                                  "value": {
                                    "type": "BinaryExpression",
                                    "span": {
                                      "start": 1709,
                                      "end": 1756
                                    },
                                    "operator": "||",
                                    "left": {
                                      "type": "MemberExpression",
                                      "span": {
                                        "start": 1709,
                                        "end": 1722
                                      },
                                      "object": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 1709,
                                          "end": 1714
                                        },
                                        "ctxt": 7,
                                        "value": "error",
                                        "optional": false
                                      },
                                      "property": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 1715,
                                          "end": 1722
                                        },
                                        "value": "message"
                                      }
                                    },
                                    "right": {
                                      "type": "TemplateLiteral",
                                      "span": {
                                        "start": 1726,
                                        "end": 1756
                                      },
                                      "expressions": [
                                        {
                                          "type": "Identifier",
                                          "span": {
                                            "start": 1752,
                                            "end": 1754
                                          },
                                          "ctxt": 3,
                                          "value": "id",
                                          "optional": false
                                        }
                                      ],
                                      "quasis": [
                                        {
                                          "type": "TemplateElement",
                                          "span": {
                                            "start": 1727,
                                            "end": 1750
                                          },
                                          "tail": false,
                                          "cooked": "Error in server action ",
                                          "raw": "Error in server action "
                                        },
                                        {
                                          "type": "TemplateElement",
                                          "span": {
                                            "start": 1755,
                                            "end": 1755
                                          },
                                          "tail": true,
                                          "cooked": "",
                                          "raw": ""
                                        }
                                      ]
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    }
                  ]
                }
              },
              "finalizer": null
            }
          ]
        },
        "generator": false,
        "async": true,
        "typeParameters": null,
        "returnType": null
      }
    }
  ],
  "interpreter": null
}
}