/* This file is auto-generated by Forket. Don't change it manually. */

export default function () {
  return {
  "type": "Module",
  "span": {
    "start": 1268,
    "end": 2112
  },
  "body": [
    {
      "type": "ExportDefaultDeclaration",
      "span": {
        "start": 1268,
        "end": 2112
      },
      "decl": {
        "type": "FunctionExpression",
        "identifier": {
          "type": "Identifier",
          "span": {
            "start": 1298,
            "end": 1317
          },
          "ctxt": 2,
          "value": "forketServerActions",
          "optional": false
        },
        "params": [
          {
            "type": "Parameter",
            "span": {
              "start": 1318,
              "end": 1321
            },
            "decorators": [],
            "pat": {
              "type": "Identifier",
              "span": {
                "start": 1318,
                "end": 1321
              },
              "ctxt": 3,
              "value": "req",
              "optional": false,
              "typeAnnotation": null
            }
          },
          {
            "type": "Parameter",
            "span": {
              "start": 1323,
              "end": 1326
            },
            "decorators": [],
            "pat": {
              "type": "Identifier",
              "span": {
                "start": 1323,
                "end": 1326
              },
              "ctxt": 3,
              "value": "res",
              "optional": false,
              "typeAnnotation": null
            }
          }
        ],
        "decorators": [],
        "span": {
          "start": 1283,
          "end": 2112
        },
        "ctxt": 3,
        "body": {
          "type": "BlockStatement",
          "span": {
            "start": 1328,
            "end": 2112
          },
          "ctxt": 3,
          "stmts": [
            {
              "type": "ExpressionStatement",
              "span": {
                "start": 1332,
                "end": 1382
              },
              "expression": {
                "type": "CallExpression",
                "span": {
                  "start": 1332,
                  "end": 1381
                },
                "ctxt": 0,
                "callee": {
                  "type": "MemberExpression",
                  "span": {
                    "start": 1332,
                    "end": 1345
                  },
                  "object": {
                    "type": "Identifier",
                    "span": {
                      "start": 1332,
                      "end": 1335
                    },
                    "ctxt": 3,
                    "value": "res",
                    "optional": false
                  },
                  "property": {
                    "type": "Identifier",
                    "span": {
                      "start": 1336,
                      "end": 1345
                    },
                    "value": "setHeader"
                  }
                },
                "arguments": [
                  {
                    "spread": null,
                    "expression": {
                      "type": "StringLiteral",
                      "span": {
                        "start": 1346,
                        "end": 1360
                      },
                      "value": "Content-Type",
                      "raw": "\"Content-Type\""
                    }
                  },
                  {
                    "spread": null,
                    "expression": {
                      "type": "StringLiteral",
                      "span": {
                        "start": 1362,
                        "end": 1380
                      },
                      "value": "application/json",
                      "raw": "\"application/json\""
                    }
                  }
                ],
                "typeArguments": null
              }
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1385,
                "end": 1557
              },
              "test": {
                "type": "BinaryExpression",
                "span": {
                  "start": 1389,
                  "end": 1412
                },
                "operator": "&&",
                "left": {
                  "type": "UnaryExpression",
                  "span": {
                    "start": 1389,
                    "end": 1398
                  },
                  "operator": "!",
                  "argument": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1390,
                      "end": 1398
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1390,
                        "end": 1393
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1394,
                        "end": 1398
                      },
                      "value": "body"
                    }
                  }
                },
                "right": {
                  "type": "UnaryExpression",
                  "span": {
                    "start": 1402,
                    "end": 1412
                  },
                  "operator": "!",
                  "argument": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1403,
                      "end": 1412
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1403,
                        "end": 1406
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1407,
                        "end": 1412
                      },
                      "value": "files"
                    }
                  }
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1414,
                  "end": 1557
                },
                "ctxt": 4,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1420,
                      "end": 1484
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1420,
                        "end": 1483
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1420,
                          "end": 1432
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1420,
                            "end": 1427
                          },
                          "ctxt": 1,
                          "value": "console",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1428,
                            "end": 1432
                          },
                          "value": "warn"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "TemplateLiteral",
                            "span": {
                              "start": 1433,
                              "end": 1482
                            },
                            "expressions": [],
                            "quasis": [
                              {
                                "type": "TemplateElement",
                                "span": {
                                  "start": 1434,
                                  "end": 1481
                                },
                                "tail": true,
                                "cooked": "‎𐂐 Forket: the request object has no body.",
                                "raw": "‎𐂐 Forket: the request object has no body."
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1489,
                      "end": 1541
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1489,
                        "end": 1540
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1489,
                          "end": 1509
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1489,
                            "end": 1504
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1489,
                              "end": 1499
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1489,
                                "end": 1492
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1493,
                                "end": 1499
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1500,
                                  "end": 1503
                                },
                                "value": 400,
                                "raw": "400"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1505,
                            "end": 1509
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1510,
                              "end": 1539
                            },
                            "properties": [
                              {
                                "type": "KeyValueProperty",
                                "key": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1512,
                                    "end": 1517
                                  },
                                  "value": "error"
                                },
                                "value": {
                                  "type": "StringLiteral",
                                  "span": {
                                    "start": 1519,
                                    "end": 1537
                                  },
                                  "value": "No body provided",
                                  "raw": "\"No body provided\""
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ReturnStatement",
                    "span": {
                      "start": 1546,
                      "end": 1553
                    },
                    "argument": null
                  }
                ]
              },
              "alternate": null
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1560,
                "end": 1730
              },
              "test": {
                "type": "UnaryExpression",
                "span": {
                  "start": 1564,
                  "end": 1584
                },
                "operator": "!",
                "argument": {
                  "type": "MemberExpression",
                  "span": {
                    "start": 1565,
                    "end": 1584
                  },
                  "object": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1565,
                      "end": 1573
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1565,
                        "end": 1568
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1569,
                        "end": 1573
                      },
                      "value": "body"
                    }
                  },
                  "property": {
                    "type": "Identifier",
                    "span": {
                      "start": 1574,
                      "end": 1584
                    },
                    "value": "__actionId"
                  }
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1586,
                  "end": 1730
                },
                "ctxt": 5,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1592,
                      "end": 1659
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1592,
                        "end": 1658
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1592,
                          "end": 1604
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1592,
                            "end": 1599
                          },
                          "ctxt": 1,
                          "value": "console",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1600,
                            "end": 1604
                          },
                          "value": "warn"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "TemplateLiteral",
                            "span": {
                              "start": 1605,
                              "end": 1657
                            },
                            "expressions": [],
                            "quasis": [
                              {
                                "type": "TemplateElement",
                                "span": {
                                  "start": 1606,
                                  "end": 1656
                                },
                                "tail": true,
                                "cooked": "‎𐂐 Forket: the request object body has no id.",
                                "raw": "‎𐂐 Forket: the request object body has no id."
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1664,
                      "end": 1714
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1664,
                        "end": 1713
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1664,
                          "end": 1684
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1664,
                            "end": 1679
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1664,
                              "end": 1674
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1664,
                                "end": 1667
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1668,
                                "end": 1674
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1675,
                                  "end": 1678
                                },
                                "value": 400,
                                "raw": "400"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1680,
                            "end": 1684
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1685,
                              "end": 1712
                            },
                            "properties": [
                              {
                                "type": "KeyValueProperty",
                                "key": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1687,
                                    "end": 1692
                                  },
                                  "value": "error"
                                },
                                "value": {
                                  "type": "StringLiteral",
                                  "span": {
                                    "start": 1694,
                                    "end": 1710
                                  },
                                  "value": "No id provided",
                                  "raw": "\"No id provided\""
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ReturnStatement",
                    "span": {
                      "start": 1719,
                      "end": 1726
                    },
                    "argument": null
                  }
                ]
              },
              "alternate": null
            },
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 1733,
                "end": 1764
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 1739,
                    "end": 1763
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 1739,
                      "end": 1741
                    },
                    "ctxt": 3,
                    "value": "id",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1744,
                      "end": 1763
                    },
                    "object": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 1744,
                        "end": 1752
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 1744,
                          "end": 1747
                        },
                        "ctxt": 3,
                        "value": "req",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 1748,
                          "end": 1752
                        },
                        "value": "body"
                      }
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1753,
                        "end": 1763
                      },
                      "value": "__actionId"
                    }
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "TryStatement",
              "span": {
                "start": 1767,
                "end": 2110
              },
              "block": {
                "type": "BlockStatement",
                "span": {
                  "start": 1771,
                  "end": 1930
                },
                "ctxt": 6,
                "stmts": [
                  {
                    "type": "VariableDeclaration",
                    "span": {
                      "start": 1777,
                      "end": 1825
                    },
                    "ctxt": 0,
                    "kind": "const",
                    "declare": false,
                    "declarations": [
                      {
                        "type": "VariableDeclarator",
                        "span": {
                          "start": 1783,
                          "end": 1824
                        },
                        "id": {
                          "type": "Identifier",
                          "span": {
                            "start": 1783,
                            "end": 1790
                          },
                          "ctxt": 6,
                          "value": "context",
                          "optional": false,
                          "typeAnnotation": null
                        },
                        "init": {
                          "type": "ObjectExpression",
                          "span": {
                            "start": 1793,
                            "end": 1824
                          },
                          "properties": [
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1795,
                                  "end": 1802
                                },
                                "value": "request"
                              },
                              "value": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1804,
                                  "end": 1807
                                },
                                "ctxt": 3,
                                "value": "req",
                                "optional": false
                              }
                            },
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1809,
                                  "end": 1817
                                },
                                "value": "response"
                              },
                              "value": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1819,
                                  "end": 1822
                                },
                                "ctxt": 3,
                                "value": "res",
                                "optional": false
                              }
                            }
                          ]
                        },
                        "definite": false
                      }
                    ]
                  },
                  {
                    "type": "VariableDeclaration",
                    "span": {
                      "start": 1830,
                      "end": 1888
                    },
                    "ctxt": 0,
                    "kind": "const",
                    "declare": false,
                    "declarations": [
                      {
                        "type": "VariableDeclarator",
                        "span": {
                          "start": 1836,
                          "end": 1887
                        },
                        "id": {
                          "type": "Identifier",
                          "span": {
                            "start": 1836,
                            "end": 1842
                          },
                          "ctxt": 6,
                          "value": "result",
                          "optional": false,
                          "typeAnnotation": null
                        },
                        "init": {
                          "type": "AwaitExpression",
                          "span": {
                            "start": 1845,
                            "end": 1887
                          },
                          "argument": {
                            "type": "CallExpression",
                            "span": {
                              "start": 1851,
                              "end": 1887
                            },
                            "ctxt": 0,
                            "callee": {
                              "type": "MemberExpression",
                              "span": {
                                "start": 1851,
                                "end": 1862
                              },
                              "object": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1851,
                                  "end": 1858
                                },
                                "ctxt": 1,
                                "value": "actions",
                                "optional": false
                              },
                              "property": {
                                "type": "Computed",
                                "span": {
                                  "start": 1858,
                                  "end": 1862
                                },
                                "expression": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1859,
                                    "end": 1861
                                  },
                                  "ctxt": 3,
                                  "value": "id",
                                  "optional": false
                                }
                              }
                            },
                            "arguments": [
                              {
                                "spread": null,
                                "expression": {
                                  "type": "BinaryExpression",
                                  "span": {
                                    "start": 1863,
                                    "end": 1877
                                  },
                                  "operator": "||",
                                  "left": {
                                    "type": "MemberExpression",
                                    "span": {
                                      "start": 1863,
                                      "end": 1871
                                    },
                                    "object": {
                                      "type": "Identifier",
                                      "span": {
                                        "start": 1863,
                                        "end": 1866
                                      },
                                      "ctxt": 3,
                                      "value": "req",
                                      "optional": false
                                    },
                                    "property": {
                                      "type": "Identifier",
                                      "span": {
                                        "start": 1867,
                                        "end": 1871
                                      },
                                      "value": "body"
                                    }
                                  },
                                  "right": {
                                    "type": "ObjectExpression",
                                    "span": {
                                      "start": 1875,
                                      "end": 1877
                                    },
                                    "properties": []
                                  }
                                }
                              },
                              {
                                "spread": null,
                                "expression": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1879,
                                    "end": 1886
                                  },
                                  "ctxt": 6,
                                  "value": "context",
                                  "optional": false
                                }
                              }
                            ],
                            "typeArguments": null
                          }
                        },
                        "definite": false
                      }
                    ]
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1893,
                      "end": 1926
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1893,
                        "end": 1925
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1893,
                          "end": 1913
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1893,
                            "end": 1908
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1893,
                              "end": 1903
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1893,
                                "end": 1896
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1897,
                                "end": 1903
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1904,
                                  "end": 1907
                                },
                                "value": 200,
                                "raw": "200"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1909,
                            "end": 1913
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1914,
                              "end": 1924
                            },
                            "properties": [
                              {
                                "type": "Identifier",
                                "span": {
                                  "start": 1916,
                                  "end": 1922
                                },
                                "ctxt": 6,
                                "value": "result",
                                "optional": false
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  }
                ]
              },
              "handler": {
                "type": "CatchClause",
                "span": {
                  "start": 1931,
                  "end": 2110
                },
                "param": {
                  "type": "Identifier",
                  "span": {
                    "start": 1937,
                    "end": 1942
                  },
                  "ctxt": 7,
                  "value": "error",
                  "optional": false,
                  "typeAnnotation": null
                },
                "body": {
                  "type": "BlockStatement",
                  "span": {
                    "start": 1944,
                    "end": 2110
                  },
                  "ctxt": 7,
                  "stmts": [
                    {
                      "type": "ExpressionStatement",
                      "span": {
                        "start": 1950,
                        "end": 2020
                      },
                      "expression": {
                        "type": "CallExpression",
                        "span": {
                          "start": 1950,
                          "end": 2019
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "MemberExpression",
                          "span": {
                            "start": 1950,
                            "end": 1963
                          },
                          "object": {
                            "type": "Identifier",
                            "span": {
                              "start": 1950,
                              "end": 1957
                            },
                            "ctxt": 1,
                            "value": "console",
                            "optional": false
                          },
                          "property": {
                            "type": "Identifier",
                            "span": {
                              "start": 1958,
                              "end": 1963
                            },
                            "value": "error"
                          }
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "TemplateLiteral",
                              "span": {
                                "start": 1964,
                                "end": 2011
                              },
                              "expressions": [
                                {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 2006,
                                    "end": 2008
                                  },
                                  "ctxt": 3,
                                  "value": "id",
                                  "optional": false
                                }
                              ],
                              "quasis": [
                                {
                                  "type": "TemplateElement",
                                  "span": {
                                    "start": 1965,
                                    "end": 2004
                                  },
                                  "tail": false,
                                  "cooked": "‎𐂐 Forket: error in server action ",
                                  "raw": "‎𐂐 Forket: error in server action "
                                },
                                {
                                  "type": "TemplateElement",
                                  "span": {
                                    "start": 2009,
                                    "end": 2010
                                  },
                                  "tail": true,
                                  "cooked": ":",
                                  "raw": ":"
                                }
                              ]
                            }
                          },
                          {
                            "spread": null,
                            "expression": {
                              "type": "Identifier",
                              "span": {
                                "start": 2013,
                                "end": 2018
                              },
                              "ctxt": 7,
                              "value": "error",
                              "optional": false
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    },
                    {
                      "type": "ExpressionStatement",
                      "span": {
                        "start": 2025,
                        "end": 2106
                      },
                      "expression": {
                        "type": "CallExpression",
                        "span": {
                          "start": 2025,
                          "end": 2105
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "MemberExpression",
                          "span": {
                            "start": 2025,
                            "end": 2045
                          },
                          "object": {
                            "type": "CallExpression",
                            "span": {
                              "start": 2025,
                              "end": 2040
                            },
                            "ctxt": 0,
                            "callee": {
                              "type": "MemberExpression",
                              "span": {
                                "start": 2025,
                                "end": 2035
                              },
                              "object": {
                                "type": "Identifier",
                                "span": {
                                  "start": 2025,
                                  "end": 2028
                                },
                                "ctxt": 3,
                                "value": "res",
                                "optional": false
                              },
                              "property": {
                                "type": "Identifier",
                                "span": {
                                  "start": 2029,
                                  "end": 2035
                                },
                                "value": "status"
                              }
                            },
                            "arguments": [
                              {
                                "spread": null,
                                "expression": {
                                  "type": "NumericLiteral",
                                  "span": {
                                    "start": 2036,
                                    "end": 2039
                                  },
                                  "value": 200,
                                  "raw": "200"
                                }
                              }
                            ],
                            "typeArguments": null
                          },
                          "property": {
                            "type": "Identifier",
                            "span": {
                              "start": 2041,
                              "end": 2045
                            },
                            "value": "json"
                          }
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "ObjectExpression",
                              "span": {
                                "start": 2046,
                                "end": 2104
                              },
                              "properties": [
                                {
                                  "type": "KeyValueProperty",
                                  "key": {
                                    "type": "Identifier",
                                    "span": {
                                      "start": 2048,
                                      "end": 2053
                                    },
                                    "value": "error"
                                  },
                                  "value": {
                                    "type": "BinaryExpression",
                                    "span": {
                                      "start": 2055,
                                      "end": 2102
                                    },
                                    "operator": "||",
                                    "left": {
                                      "type": "MemberExpression",
                                      "span": {
                                        "start": 2055,
                                        "end": 2068
                                      },
                                      "object": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 2055,
                                          "end": 2060
                                        },
                                        "ctxt": 7,
                                        "value": "error",
                                        "optional": false
                                      },
                                      "property": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 2061,
                                          "end": 2068
                                        },
                                        "value": "message"
                                      }
                                    },
                                    "right": {
                                      "type": "TemplateLiteral",
                                      "span": {
                                        "start": 2072,
                                        "end": 2102
                                      },
                                      "expressions": [
                                        {
                                          "type": "Identifier",
                                          "span": {
                                            "start": 2098,
                                            "end": 2100
                                          },
                                          "ctxt": 3,
                                          "value": "id",
                                          "optional": false
                                        }
                                      ],
                                      "quasis": [
                                        {
                                          "type": "TemplateElement",
                                          "span": {
                                            "start": 2073,
                                            "end": 2096
                                          },
                                          "tail": false,
                                          "cooked": "Error in server action ",
                                          "raw": "Error in server action "
                                        },
                                        {
                                          "type": "TemplateElement",
                                          "span": {
                                            "start": 2101,
                                            "end": 2101
                                          },
                                          "tail": true,
                                          "cooked": "",
                                          "raw": ""
                                        }
                                      ]
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    }
                  ]
                }
              },
              "finalizer": null
            }
          ]
        },
        "generator": false,
        "async": true,
        "typeParameters": null,
        "returnType": null
      }
    }
  ],
  "interpreter": null
}
}