/* This file is auto-generated by Forket. Don't change it manually. */

export default function () {
  return {
  "type": "Module",
  "span": {
    "start": 1229,
    "end": 2073
  },
  "body": [
    {
      "type": "ExportDefaultDeclaration",
      "span": {
        "start": 1229,
        "end": 2073
      },
      "decl": {
        "type": "FunctionExpression",
        "identifier": {
          "type": "Identifier",
          "span": {
            "start": 1259,
            "end": 1278
          },
          "ctxt": 2,
          "value": "forketServerActions",
          "optional": false
        },
        "params": [
          {
            "type": "Parameter",
            "span": {
              "start": 1279,
              "end": 1282
            },
            "decorators": [],
            "pat": {
              "type": "Identifier",
              "span": {
                "start": 1279,
                "end": 1282
              },
              "ctxt": 3,
              "value": "req",
              "optional": false,
              "typeAnnotation": null
            }
          },
          {
            "type": "Parameter",
            "span": {
              "start": 1284,
              "end": 1287
            },
            "decorators": [],
            "pat": {
              "type": "Identifier",
              "span": {
                "start": 1284,
                "end": 1287
              },
              "ctxt": 3,
              "value": "res",
              "optional": false,
              "typeAnnotation": null
            }
          }
        ],
        "decorators": [],
        "span": {
          "start": 1244,
          "end": 2073
        },
        "ctxt": 3,
        "body": {
          "type": "BlockStatement",
          "span": {
            "start": 1289,
            "end": 2073
          },
          "ctxt": 3,
          "stmts": [
            {
              "type": "ExpressionStatement",
              "span": {
                "start": 1293,
                "end": 1343
              },
              "expression": {
                "type": "CallExpression",
                "span": {
                  "start": 1293,
                  "end": 1342
                },
                "ctxt": 0,
                "callee": {
                  "type": "MemberExpression",
                  "span": {
                    "start": 1293,
                    "end": 1306
                  },
                  "object": {
                    "type": "Identifier",
                    "span": {
                      "start": 1293,
                      "end": 1296
                    },
                    "ctxt": 3,
                    "value": "res",
                    "optional": false
                  },
                  "property": {
                    "type": "Identifier",
                    "span": {
                      "start": 1297,
                      "end": 1306
                    },
                    "value": "setHeader"
                  }
                },
                "arguments": [
                  {
                    "spread": null,
                    "expression": {
                      "type": "StringLiteral",
                      "span": {
                        "start": 1307,
                        "end": 1321
                      },
                      "value": "Content-Type",
                      "raw": "\"Content-Type\""
                    }
                  },
                  {
                    "spread": null,
                    "expression": {
                      "type": "StringLiteral",
                      "span": {
                        "start": 1323,
                        "end": 1341
                      },
                      "value": "application/json",
                      "raw": "\"application/json\""
                    }
                  }
                ],
                "typeArguments": null
              }
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1346,
                "end": 1518
              },
              "test": {
                "type": "BinaryExpression",
                "span": {
                  "start": 1350,
                  "end": 1373
                },
                "operator": "&&",
                "left": {
                  "type": "UnaryExpression",
                  "span": {
                    "start": 1350,
                    "end": 1359
                  },
                  "operator": "!",
                  "argument": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1351,
                      "end": 1359
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1351,
                        "end": 1354
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1355,
                        "end": 1359
                      },
                      "value": "body"
                    }
                  }
                },
                "right": {
                  "type": "UnaryExpression",
                  "span": {
                    "start": 1363,
                    "end": 1373
                  },
                  "operator": "!",
                  "argument": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1364,
                      "end": 1373
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1364,
                        "end": 1367
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1368,
                        "end": 1373
                      },
                      "value": "files"
                    }
                  }
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1375,
                  "end": 1518
                },
                "ctxt": 4,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1381,
                      "end": 1445
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1381,
                        "end": 1444
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1381,
                          "end": 1393
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1381,
                            "end": 1388
                          },
                          "ctxt": 1,
                          "value": "console",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1389,
                            "end": 1393
                          },
                          "value": "warn"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "TemplateLiteral",
                            "span": {
                              "start": 1394,
                              "end": 1443
                            },
                            "expressions": [],
                            "quasis": [
                              {
                                "type": "TemplateElement",
                                "span": {
                                  "start": 1395,
                                  "end": 1442
                                },
                                "tail": true,
                                "cooked": "‎𐂐 Forket: the request object has no body.",
                                "raw": "‎𐂐 Forket: the request object has no body."
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1450,
                      "end": 1502
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1450,
                        "end": 1501
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1450,
                          "end": 1470
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1450,
                            "end": 1465
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1450,
                              "end": 1460
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1450,
                                "end": 1453
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1454,
                                "end": 1460
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1461,
                                  "end": 1464
                                },
                                "value": 400,
                                "raw": "400"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1466,
                            "end": 1470
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1471,
                              "end": 1500
                            },
                            "properties": [
                              {
                                "type": "KeyValueProperty",
                                "key": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1473,
                                    "end": 1478
                                  },
                                  "value": "error"
                                },
                                "value": {
                                  "type": "StringLiteral",
                                  "span": {
                                    "start": 1480,
                                    "end": 1498
                                  },
                                  "value": "No body provided",
                                  "raw": "\"No body provided\""
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ReturnStatement",
                    "span": {
                      "start": 1507,
                      "end": 1514
                    },
                    "argument": null
                  }
                ]
              },
              "alternate": null
            },
            {
              "type": "IfStatement",
              "span": {
                "start": 1521,
                "end": 1691
              },
              "test": {
                "type": "UnaryExpression",
                "span": {
                  "start": 1525,
                  "end": 1545
                },
                "operator": "!",
                "argument": {
                  "type": "MemberExpression",
                  "span": {
                    "start": 1526,
                    "end": 1545
                  },
                  "object": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1526,
                      "end": 1534
                    },
                    "object": {
                      "type": "Identifier",
                      "span": {
                        "start": 1526,
                        "end": 1529
                      },
                      "ctxt": 3,
                      "value": "req",
                      "optional": false
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1530,
                        "end": 1534
                      },
                      "value": "body"
                    }
                  },
                  "property": {
                    "type": "Identifier",
                    "span": {
                      "start": 1535,
                      "end": 1545
                    },
                    "value": "__actionId"
                  }
                }
              },
              "consequent": {
                "type": "BlockStatement",
                "span": {
                  "start": 1547,
                  "end": 1691
                },
                "ctxt": 5,
                "stmts": [
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1553,
                      "end": 1620
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1553,
                        "end": 1619
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1553,
                          "end": 1565
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 1553,
                            "end": 1560
                          },
                          "ctxt": 1,
                          "value": "console",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1561,
                            "end": 1565
                          },
                          "value": "warn"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "TemplateLiteral",
                            "span": {
                              "start": 1566,
                              "end": 1618
                            },
                            "expressions": [],
                            "quasis": [
                              {
                                "type": "TemplateElement",
                                "span": {
                                  "start": 1567,
                                  "end": 1617
                                },
                                "tail": true,
                                "cooked": "‎𐂐 Forket: the request object body has no id.",
                                "raw": "‎𐂐 Forket: the request object body has no id."
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1625,
                      "end": 1675
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1625,
                        "end": 1674
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1625,
                          "end": 1645
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1625,
                            "end": 1640
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1625,
                              "end": 1635
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1625,
                                "end": 1628
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1629,
                                "end": 1635
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1636,
                                  "end": 1639
                                },
                                "value": 400,
                                "raw": "400"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1641,
                            "end": 1645
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1646,
                              "end": 1673
                            },
                            "properties": [
                              {
                                "type": "KeyValueProperty",
                                "key": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1648,
                                    "end": 1653
                                  },
                                  "value": "error"
                                },
                                "value": {
                                  "type": "StringLiteral",
                                  "span": {
                                    "start": 1655,
                                    "end": 1671
                                  },
                                  "value": "No id provided",
                                  "raw": "\"No id provided\""
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  },
                  {
                    "type": "ReturnStatement",
                    "span": {
                      "start": 1680,
                      "end": 1687
                    },
                    "argument": null
                  }
                ]
              },
              "alternate": null
            },
            {
              "type": "VariableDeclaration",
              "span": {
                "start": 1694,
                "end": 1725
              },
              "ctxt": 0,
              "kind": "const",
              "declare": false,
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "span": {
                    "start": 1700,
                    "end": 1724
                  },
                  "id": {
                    "type": "Identifier",
                    "span": {
                      "start": 1700,
                      "end": 1702
                    },
                    "ctxt": 3,
                    "value": "id",
                    "optional": false,
                    "typeAnnotation": null
                  },
                  "init": {
                    "type": "MemberExpression",
                    "span": {
                      "start": 1705,
                      "end": 1724
                    },
                    "object": {
                      "type": "MemberExpression",
                      "span": {
                        "start": 1705,
                        "end": 1713
                      },
                      "object": {
                        "type": "Identifier",
                        "span": {
                          "start": 1705,
                          "end": 1708
                        },
                        "ctxt": 3,
                        "value": "req",
                        "optional": false
                      },
                      "property": {
                        "type": "Identifier",
                        "span": {
                          "start": 1709,
                          "end": 1713
                        },
                        "value": "body"
                      }
                    },
                    "property": {
                      "type": "Identifier",
                      "span": {
                        "start": 1714,
                        "end": 1724
                      },
                      "value": "__actionId"
                    }
                  },
                  "definite": false
                }
              ]
            },
            {
              "type": "TryStatement",
              "span": {
                "start": 1728,
                "end": 2071
              },
              "block": {
                "type": "BlockStatement",
                "span": {
                  "start": 1732,
                  "end": 1891
                },
                "ctxt": 6,
                "stmts": [
                  {
                    "type": "VariableDeclaration",
                    "span": {
                      "start": 1738,
                      "end": 1786
                    },
                    "ctxt": 0,
                    "kind": "const",
                    "declare": false,
                    "declarations": [
                      {
                        "type": "VariableDeclarator",
                        "span": {
                          "start": 1744,
                          "end": 1785
                        },
                        "id": {
                          "type": "Identifier",
                          "span": {
                            "start": 1744,
                            "end": 1751
                          },
                          "ctxt": 6,
                          "value": "context",
                          "optional": false,
                          "typeAnnotation": null
                        },
                        "init": {
                          "type": "ObjectExpression",
                          "span": {
                            "start": 1754,
                            "end": 1785
                          },
                          "properties": [
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1756,
                                  "end": 1763
                                },
                                "value": "request"
                              },
                              "value": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1765,
                                  "end": 1768
                                },
                                "ctxt": 3,
                                "value": "req",
                                "optional": false
                              }
                            },
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1770,
                                  "end": 1778
                                },
                                "value": "response"
                              },
                              "value": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1780,
                                  "end": 1783
                                },
                                "ctxt": 3,
                                "value": "res",
                                "optional": false
                              }
                            }
                          ]
                        },
                        "definite": false
                      }
                    ]
                  },
                  {
                    "type": "VariableDeclaration",
                    "span": {
                      "start": 1791,
                      "end": 1849
                    },
                    "ctxt": 0,
                    "kind": "const",
                    "declare": false,
                    "declarations": [
                      {
                        "type": "VariableDeclarator",
                        "span": {
                          "start": 1797,
                          "end": 1848
                        },
                        "id": {
                          "type": "Identifier",
                          "span": {
                            "start": 1797,
                            "end": 1803
                          },
                          "ctxt": 6,
                          "value": "result",
                          "optional": false,
                          "typeAnnotation": null
                        },
                        "init": {
                          "type": "AwaitExpression",
                          "span": {
                            "start": 1806,
                            "end": 1848
                          },
                          "argument": {
                            "type": "CallExpression",
                            "span": {
                              "start": 1812,
                              "end": 1848
                            },
                            "ctxt": 0,
                            "callee": {
                              "type": "MemberExpression",
                              "span": {
                                "start": 1812,
                                "end": 1823
                              },
                              "object": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1812,
                                  "end": 1819
                                },
                                "ctxt": 1,
                                "value": "actions",
                                "optional": false
                              },
                              "property": {
                                "type": "Computed",
                                "span": {
                                  "start": 1819,
                                  "end": 1823
                                },
                                "expression": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1820,
                                    "end": 1822
                                  },
                                  "ctxt": 3,
                                  "value": "id",
                                  "optional": false
                                }
                              }
                            },
                            "arguments": [
                              {
                                "spread": null,
                                "expression": {
                                  "type": "BinaryExpression",
                                  "span": {
                                    "start": 1824,
                                    "end": 1838
                                  },
                                  "operator": "||",
                                  "left": {
                                    "type": "MemberExpression",
                                    "span": {
                                      "start": 1824,
                                      "end": 1832
                                    },
                                    "object": {
                                      "type": "Identifier",
                                      "span": {
                                        "start": 1824,
                                        "end": 1827
                                      },
                                      "ctxt": 3,
                                      "value": "req",
                                      "optional": false
                                    },
                                    "property": {
                                      "type": "Identifier",
                                      "span": {
                                        "start": 1828,
                                        "end": 1832
                                      },
                                      "value": "body"
                                    }
                                  },
                                  "right": {
                                    "type": "ObjectExpression",
                                    "span": {
                                      "start": 1836,
                                      "end": 1838
                                    },
                                    "properties": []
                                  }
                                }
                              },
                              {
                                "spread": null,
                                "expression": {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1840,
                                    "end": 1847
                                  },
                                  "ctxt": 6,
                                  "value": "context",
                                  "optional": false
                                }
                              }
                            ],
                            "typeArguments": null
                          }
                        },
                        "definite": false
                      }
                    ]
                  },
                  {
                    "type": "ExpressionStatement",
                    "span": {
                      "start": 1854,
                      "end": 1887
                    },
                    "expression": {
                      "type": "CallExpression",
                      "span": {
                        "start": 1854,
                        "end": 1886
                      },
                      "ctxt": 0,
                      "callee": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 1854,
                          "end": 1874
                        },
                        "object": {
                          "type": "CallExpression",
                          "span": {
                            "start": 1854,
                            "end": 1869
                          },
                          "ctxt": 0,
                          "callee": {
                            "type": "MemberExpression",
                            "span": {
                              "start": 1854,
                              "end": 1864
                            },
                            "object": {
                              "type": "Identifier",
                              "span": {
                                "start": 1854,
                                "end": 1857
                              },
                              "ctxt": 3,
                              "value": "res",
                              "optional": false
                            },
                            "property": {
                              "type": "Identifier",
                              "span": {
                                "start": 1858,
                                "end": 1864
                              },
                              "value": "status"
                            }
                          },
                          "arguments": [
                            {
                              "spread": null,
                              "expression": {
                                "type": "NumericLiteral",
                                "span": {
                                  "start": 1865,
                                  "end": 1868
                                },
                                "value": 200,
                                "raw": "200"
                              }
                            }
                          ],
                          "typeArguments": null
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 1870,
                            "end": 1874
                          },
                          "value": "json"
                        }
                      },
                      "arguments": [
                        {
                          "spread": null,
                          "expression": {
                            "type": "ObjectExpression",
                            "span": {
                              "start": 1875,
                              "end": 1885
                            },
                            "properties": [
                              {
                                "type": "Identifier",
                                "span": {
                                  "start": 1877,
                                  "end": 1883
                                },
                                "ctxt": 6,
                                "value": "result",
                                "optional": false
                              }
                            ]
                          }
                        }
                      ],
                      "typeArguments": null
                    }
                  }
                ]
              },
              "handler": {
                "type": "CatchClause",
                "span": {
                  "start": 1892,
                  "end": 2071
                },
                "param": {
                  "type": "Identifier",
                  "span": {
                    "start": 1898,
                    "end": 1903
                  },
                  "ctxt": 7,
                  "value": "error",
                  "optional": false,
                  "typeAnnotation": null
                },
                "body": {
                  "type": "BlockStatement",
                  "span": {
                    "start": 1905,
                    "end": 2071
                  },
                  "ctxt": 7,
                  "stmts": [
                    {
                      "type": "ExpressionStatement",
                      "span": {
                        "start": 1911,
                        "end": 1981
                      },
                      "expression": {
                        "type": "CallExpression",
                        "span": {
                          "start": 1911,
                          "end": 1980
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "MemberExpression",
                          "span": {
                            "start": 1911,
                            "end": 1924
                          },
                          "object": {
                            "type": "Identifier",
                            "span": {
                              "start": 1911,
                              "end": 1918
                            },
                            "ctxt": 1,
                            "value": "console",
                            "optional": false
                          },
                          "property": {
                            "type": "Identifier",
                            "span": {
                              "start": 1919,
                              "end": 1924
                            },
                            "value": "error"
                          }
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "TemplateLiteral",
                              "span": {
                                "start": 1925,
                                "end": 1972
                              },
                              "expressions": [
                                {
                                  "type": "Identifier",
                                  "span": {
                                    "start": 1967,
                                    "end": 1969
                                  },
                                  "ctxt": 3,
                                  "value": "id",
                                  "optional": false
                                }
                              ],
                              "quasis": [
                                {
                                  "type": "TemplateElement",
                                  "span": {
                                    "start": 1926,
                                    "end": 1965
                                  },
                                  "tail": false,
                                  "cooked": "‎𐂐 Forket: error in server action ",
                                  "raw": "‎𐂐 Forket: error in server action "
                                },
                                {
                                  "type": "TemplateElement",
                                  "span": {
                                    "start": 1970,
                                    "end": 1971
                                  },
                                  "tail": true,
                                  "cooked": ":",
                                  "raw": ":"
                                }
                              ]
                            }
                          },
                          {
                            "spread": null,
                            "expression": {
                              "type": "Identifier",
                              "span": {
                                "start": 1974,
                                "end": 1979
                              },
                              "ctxt": 7,
                              "value": "error",
                              "optional": false
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    },
                    {
                      "type": "ExpressionStatement",
                      "span": {
                        "start": 1986,
                        "end": 2067
                      },
                      "expression": {
                        "type": "CallExpression",
                        "span": {
                          "start": 1986,
                          "end": 2066
                        },
                        "ctxt": 0,
                        "callee": {
                          "type": "MemberExpression",
                          "span": {
                            "start": 1986,
                            "end": 2006
                          },
                          "object": {
                            "type": "CallExpression",
                            "span": {
                              "start": 1986,
                              "end": 2001
                            },
                            "ctxt": 0,
                            "callee": {
                              "type": "MemberExpression",
                              "span": {
                                "start": 1986,
                                "end": 1996
                              },
                              "object": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1986,
                                  "end": 1989
                                },
                                "ctxt": 3,
                                "value": "res",
                                "optional": false
                              },
                              "property": {
                                "type": "Identifier",
                                "span": {
                                  "start": 1990,
                                  "end": 1996
                                },
                                "value": "status"
                              }
                            },
                            "arguments": [
                              {
                                "spread": null,
                                "expression": {
                                  "type": "NumericLiteral",
                                  "span": {
                                    "start": 1997,
                                    "end": 2000
                                  },
                                  "value": 200,
                                  "raw": "200"
                                }
                              }
                            ],
                            "typeArguments": null
                          },
                          "property": {
                            "type": "Identifier",
                            "span": {
                              "start": 2002,
                              "end": 2006
                            },
                            "value": "json"
                          }
                        },
                        "arguments": [
                          {
                            "spread": null,
                            "expression": {
                              "type": "ObjectExpression",
                              "span": {
                                "start": 2007,
                                "end": 2065
                              },
                              "properties": [
                                {
                                  "type": "KeyValueProperty",
                                  "key": {
                                    "type": "Identifier",
                                    "span": {
                                      "start": 2009,
                                      "end": 2014
                                    },
                                    "value": "error"
                                  },
                                  "value": {
                                    "type": "BinaryExpression",
                                    "span": {
                                      "start": 2016,
                                      "end": 2063
                                    },
                                    "operator": "||",
                                    "left": {
                                      "type": "MemberExpression",
                                      "span": {
                                        "start": 2016,
                                        "end": 2029
                                      },
                                      "object": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 2016,
                                          "end": 2021
                                        },
                                        "ctxt": 7,
                                        "value": "error",
                                        "optional": false
                                      },
                                      "property": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 2022,
                                          "end": 2029
                                        },
                                        "value": "message"
                                      }
                                    },
                                    "right": {
                                      "type": "TemplateLiteral",
                                      "span": {
                                        "start": 2033,
                                        "end": 2063
                                      },
                                      "expressions": [
                                        {
                                          "type": "Identifier",
                                          "span": {
                                            "start": 2059,
                                            "end": 2061
                                          },
                                          "ctxt": 3,
                                          "value": "id",
                                          "optional": false
                                        }
                                      ],
                                      "quasis": [
                                        {
                                          "type": "TemplateElement",
                                          "span": {
                                            "start": 2034,
                                            "end": 2057
                                          },
                                          "tail": false,
                                          "cooked": "Error in server action ",
                                          "raw": "Error in server action "
                                        },
                                        {
                                          "type": "TemplateElement",
                                          "span": {
                                            "start": 2062,
                                            "end": 2062
                                          },
                                          "tail": true,
                                          "cooked": "",
                                          "raw": ""
                                        }
                                      ]
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ],
                        "typeArguments": null
                      }
                    }
                  ]
                }
              },
              "finalizer": null
            }
          ]
        },
        "generator": false,
        "async": true,
        "typeParameters": null,
        "returnType": null
      }
    }
  ],
  "interpreter": null
}
}