/* This file is auto-generated by Forket. Don't change it manually. */

export default function () {
  return [
  {
    "type": "IfStatement",
    "span": {
      "start": 1181,
      "end": 1250
    },
    "test": {
      "type": "BinaryExpression",
      "span": {
        "start": 1185,
        "end": 1223
      },
      "operator": "===",
      "left": {
        "type": "UnaryExpression",
        "span": {
          "start": 1185,
          "end": 1208
        },
        "operator": "typeof",
        "argument": {
          "type": "MemberExpression",
          "span": {
            "start": 1192,
            "end": 1208
          },
          "object": {
            "type": "Identifier",
            "span": {
              "start": 1192,
              "end": 1198
            },
            "ctxt": 1,
            "value": "window",
            "optional": false
          },
          "property": {
            "type": "Identifier",
            "span": {
              "start": 1199,
              "end": 1208
            },
            "value": "FRSC_init"
          }
        }
      },
      "right": {
        "type": "StringLiteral",
        "span": {
          "start": 1213,
          "end": 1223
        },
        "value": "function",
        "raw": "\"function\""
      }
    },
    "consequent": {
      "type": "BlockStatement",
      "span": {
        "start": 1225,
        "end": 1250
      },
      "ctxt": 3,
      "stmts": [
        {
          "type": "ExpressionStatement",
          "span": {
            "start": 1229,
            "end": 1248
          },
          "expression": {
            "type": "CallExpression",
            "span": {
              "start": 1229,
              "end": 1247
            },
            "ctxt": 0,
            "callee": {
              "type": "MemberExpression",
              "span": {
                "start": 1229,
                "end": 1245
              },
              "object": {
                "type": "Identifier",
                "span": {
                  "start": 1229,
                  "end": 1235
                },
                "ctxt": 1,
                "value": "window",
                "optional": false
              },
              "property": {
                "type": "Identifier",
                "span": {
                  "start": 1236,
                  "end": 1245
                },
                "value": "FRSC_init"
              }
            },
            "arguments": [],
            "typeArguments": null
          }
        }
      ]
    },
    "alternate": null
  }
]
}