/* This file is auto-generated by Forket. Don't change it manually. */

export default function (windowKey, value) {
  return [
  {
    "type": "ExpressionStatement",
    "span": {
      "start": 845,
      "end": 862
    },
    "expression": {
      "type": "AssignmentExpression",
      "span": {
        "start": 845,
        "end": 861
      },
      "operator": "=",
      "left": {
        "type": "MemberExpression",
        "span": {
          "start": 845,
          "end": 855
        },
        "object": {
          "type": "Identifier",
          "span": {
            "start": 845,
            "end": 851
          },
          "ctxt": 1,
          "value": "window",
          "optional": false
        },
        "property": {
          "type": "Identifier",
          "span": {
            "start": 852,
            "end": 855
          },
          "value": windowKey
        }
      },
      "right": {
        "type": "Identifier",
        "span": {
          "start": 858,
          "end": 861
        },
        "ctxt": 1,
        "value": value,
        "optional": false
      }
    }
  }
]
}