/* This file is auto-generated by Forket. Don't change it manually. */

export default function (windowKey, value) {
  return [
  {
    "type": "ExpressionStatement",
    "span": {
      "start": 1019,
      "end": 1036
    },
    "expression": {
      "type": "AssignmentExpression",
      "span": {
        "start": 1019,
        "end": 1035
      },
      "operator": "=",
      "left": {
        "type": "MemberExpression",
        "span": {
          "start": 1019,
          "end": 1029
        },
        "object": {
          "type": "Identifier",
          "span": {
            "start": 1019,
            "end": 1025
          },
          "ctxt": 1,
          "value": "window",
          "optional": false
        },
        "property": {
          "type": "Identifier",
          "span": {
            "start": 1026,
            "end": 1029
          },
          "value": windowKey
        }
      },
      "right": {
        "type": "Identifier",
        "span": {
          "start": 1032,
          "end": 1035
        },
        "ctxt": 1,
        "value": value,
        "optional": false
      }
    }
  }
]
}