/* This file is auto-generated by Forket. Don't change it manually. */

export default function (windowKey, value) {
  return [
  {
    "type": "ExpressionStatement",
    "span": {
      "start": 1646,
      "end": 1663
    },
    "expression": {
      "type": "AssignmentExpression",
      "span": {
        "start": 1646,
        "end": 1662
      },
      "operator": "=",
      "left": {
        "type": "MemberExpression",
        "span": {
          "start": 1646,
          "end": 1656
        },
        "object": {
          "type": "Identifier",
          "span": {
            "start": 1646,
            "end": 1652
          },
          "ctxt": 1,
          "value": "window",
          "optional": false
        },
        "property": {
          "type": "Identifier",
          "span": {
            "start": 1653,
            "end": 1656
          },
          "value": windowKey
        }
      },
      "right": {
        "type": "Identifier",
        "span": {
          "start": 1659,
          "end": 1662
        },
        "ctxt": 1,
        "value": value,
        "optional": false
      }
    }
  }
]
}