/* This file is auto-generated by Forket. Don't change it manually. */

export default function (what, where) {
  return [
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 809,
      "end": 844
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 815,
          "end": 843
        },
        "id": {
          "type": "ObjectPattern",
          "span": {
            "start": 815,
            "end": 824
          },
          "properties": [
            {
              "type": "AssignmentPatternProperty",
              "span": {
                "start": 817,
                "end": 822
              },
              "key": {
                "type": "Identifier",
                "span": {
                  "start": 817,
                  "end": 822
                },
                "ctxt": 2,
                "value": what,
                "optional": false,
                "typeAnnotation": null
              },
              "value": null
            }
          ],
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "CallExpression",
          "span": {
            "start": 827,
            "end": 843
          },
          "ctxt": 0,
          "callee": {
            "type": "Identifier",
            "span": {
              "start": 827,
              "end": 834
            },
            "ctxt": 1,
            "value": "require",
            "optional": false
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "StringLiteral",
                "span": {
                  "start": 835,
                  "end": 842
                },
                "value": where,
                "raw": "\"" + where + "\""
              }
            }
          ],
          "typeArguments": null
        },
        "definite": false
      }
    ]
  }
]
}