/* This file is auto-generated by Forket. Don't change it manually. */

export default function (id, componentName) {
  return {
  "type": "FunctionDeclaration",
  "identifier": {
    "type": "Identifier",
    "span": {
      "start": 10,
      "end": 23
    },
    "ctxt": 2,
    "value": componentName + "Boundary",
    "optional": false
  },
  "declare": false,
  "params": [
    {
      "type": "Parameter",
      "span": {
        "start": 24,
        "end": 29
      },
      "decorators": [],
      "pat": {
        "type": "Identifier",
        "span": {
          "start": 24,
          "end": 29
        },
        "ctxt": 3,
        "value": "props",
        "optional": false,
        "typeAnnotation": null
      }
    }
  ],
  "decorators": [],
  "span": {
    "start": 1,
    "end": 982
  },
  "ctxt": 3,
  "body": {
    "type": "BlockStatement",
    "span": {
      "start": 31,
      "end": 982
    },
    "ctxt": 3,
    "stmts": [
      {
        "type": "VariableDeclaration",
        "span": {
          "start": 35,
          "end": 103
        },
        "ctxt": 0,
        "kind": "const",
        "declare": false,
        "declarations": [
          {
            "type": "VariableDeclarator",
            "span": {
              "start": 41,
              "end": 102
            },
            "id": {
              "type": "Identifier",
              "span": {
                "start": 41,
                "end": 56
              },
              "ctxt": 3,
              "value": "serializedProps",
              "optional": false,
              "typeAnnotation": null
            },
            "init": {
              "type": "CallExpression",
              "span": {
                "start": 59,
                "end": 102
              },
              "ctxt": 0,
              "callee": {
                "type": "MemberExpression",
                "span": {
                  "start": 59,
                  "end": 73
                },
                "object": {
                  "type": "Identifier",
                  "span": {
                    "start": 59,
                    "end": 63
                  },
                  "ctxt": 1,
                  "value": "JSON",
                  "optional": false
                },
                "property": {
                  "type": "Identifier",
                  "span": {
                    "start": 64,
                    "end": 73
                  },
                  "value": "stringify"
                }
              },
              "arguments": [
                {
                  "spread": null,
                  "expression": {
                    "type": "CallExpression",
                    "span": {
                      "start": 74,
                      "end": 101
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "Identifier",
                      "span": {
                        "start": 74,
                        "end": 94
                      },
                      "ctxt": 1,
                      "value": "forketSerializeProps",
                      "optional": false
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 95,
                            "end": 100
                          },
                          "ctxt": 3,
                          "value": "props",
                          "optional": false
                        }
                      }
                    ],
                    "typeArguments": null
                  }
                }
              ],
              "typeArguments": null
            },
            "definite": false
          }
        ]
      },
      {
        "type": "VariableDeclaration",
        "span": {
          "start": 106,
          "end": 144
        },
        "ctxt": 0,
        "kind": "const",
        "declare": false,
        "declarations": [
          {
            "type": "VariableDeclarator",
            "span": {
              "start": 112,
              "end": 143
            },
            "id": {
              "type": "Identifier",
              "span": {
                "start": 112,
                "end": 120
              },
              "ctxt": 3,
              "value": "children",
              "optional": false,
              "typeAnnotation": null
            },
            "init": {
              "type": "BinaryExpression",
              "span": {
                "start": 123,
                "end": 143
              },
              "operator": "||",
              "left": {
                "type": "MemberExpression",
                "span": {
                  "start": 123,
                  "end": 137
                },
                "object": {
                  "type": "Identifier",
                  "span": {
                    "start": 123,
                    "end": 128
                  },
                  "ctxt": 3,
                  "value": "props",
                  "optional": false
                },
                "property": {
                  "type": "Identifier",
                  "span": {
                    "start": 129,
                    "end": 137
                  },
                  "value": "children"
                }
              },
              "right": {
                "type": "ArrayExpression",
                "span": {
                  "start": 141,
                  "end": 143
                },
                "elements": []
              }
            },
            "definite": false
          }
        ]
      },
      {
        "type": "ReturnStatement",
        "span": {
          "start": 147,
          "end": 980
        },
        "argument": {
          "type": "ParenthesisExpression",
          "span": {
            "start": 154,
            "end": 979
          },
          "expression": {
            "type": "JSXFragment",
            "span": {
              "start": 160,
              "end": 975
            },
            "opening": {
              "type": "JSXOpeningFragment",
              "span": {
                "start": 160,
                "end": 162
              }
            },
            "children": [
              {
                "type": "JSXText",
                "span": {
                  "start": 162,
                  "end": 169
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 169,
                  "end": 590
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 170,
                      "end": 176
                    },
                    "ctxt": 1,
                    "value": "script",
                    "optional": false
                  },
                  "span": {
                    "start": 169,
                    "end": 581
                  },
                  "attributes": [
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 185,
                        "end": 573
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 185,
                          "end": 208
                        },
                        "value": "dangerouslySetInnerHTML"
                      },
                      "value": {
                        "type": "JSXExpressionContainer",
                        "span": {
                          "start": 209,
                          "end": 573
                        },
                        "expression": {
                          "type": "ObjectExpression",
                          "span": {
                            "start": 210,
                            "end": 572
                          },
                          "properties": [
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 222,
                                  "end": 228
                                },
                                "value": "__html"
                              },
                              "value": {
                                "type": "TemplateLiteral",
                                "span": {
                                  "start": 230,
                                  "end": 562
                                },
                                "expressions": [
                                  {
                                    "type": "CallExpression",
                                    "span": {
                                      "start": 290,
                                      "end": 321
                                    },
                                    "ctxt": 0,
                                    "callee": {
                                      "type": "MemberExpression",
                                      "span": {
                                        "start": 290,
                                        "end": 304
                                      },
                                      "object": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 290,
                                          "end": 294
                                        },
                                        "ctxt": 1,
                                        "value": "JSON",
                                        "optional": false
                                      },
                                      "property": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 295,
                                          "end": 304
                                        },
                                        "value": "stringify"
                                      }
                                    },
                                    "arguments": [
                                      {
                                        "spread": null,
                                        "expression": {
                                          "type": "Identifier",
                                          "span": {
                                            "start": 305,
                                            "end": 320
                                          },
                                          "ctxt": 3,
                                          "value": "serializedProps",
                                          "optional": false
                                        }
                                      }
                                    ],
                                    "typeArguments": null
                                  }
                                ],
                                "quasis": [
                                  {
                                    "type": "TemplateElement",
                                    "span": {
                                      "start": 231,
                                      "end": 288
                                    },
                                    "tail": false,
                                    "cooked": "(function () {\n          let a = [\"" + id + "\", \"" + componentName + "\", ",
                                    "raw": "(function () {\n          let a = [\"" + id + "\", \"" + componentName + "\", "
                                  },
                                  {
                                    "type": "TemplateElement",
                                    "span": {
                                      "start": 322,
                                      "end": 561
                                    },
                                    "tail": true,
                                    "cooked": "];\n          if (typeof $FRSC !== 'undefined') return $FRSC(a);\n          if (typeof $FRSC_ === 'undefined') { $FRSC_ = []; }\n          $FRSC_.push(a);\n          let me = document.currentScript;\n          if (me) me.remove();\n        })();",
                                    "raw": "];\n          if (typeof $FRSC !== 'undefined') return $FRSC(a);\n          if (typeof $FRSC_ === 'undefined') { $FRSC_ = []; }\n          $FRSC_.push(a);\n          let me = document.currentScript;\n          if (me) me.remove();\n        })();"
                                  }
                                ]
                              }
                            }
                          ]
                        }
                      }
                    }
                  ],
                  "selfClosing": false,
                  "typeArguments": null
                },
                "children": [],
                "closing": {
                  "type": "JSXClosingElement",
                  "span": {
                    "start": 581,
                    "end": 590
                  },
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 583,
                      "end": 589
                    },
                    "ctxt": 1,
                    "value": "script",
                    "optional": false
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 590,
                  "end": 597
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXExpressionContainer",
                "span": {
                  "start": 597,
                  "end": 757
                },
                "expression": {
                  "type": "BinaryExpression",
                  "span": {
                    "start": 598,
                    "end": 756
                  },
                  "operator": "&&",
                  "left": {
                    "type": "BinaryExpression",
                    "span": {
                      "start": 598,
                      "end": 629
                    },
                    "operator": "&&",
                    "left": {
                      "type": "Identifier",
                      "span": {
                        "start": 598,
                        "end": 606
                      },
                      "ctxt": 3,
                      "value": "children",
                      "optional": false
                    },
                    "right": {
                      "type": "BinaryExpression",
                      "span": {
                        "start": 610,
                        "end": 629
                      },
                      "operator": ">",
                      "left": {
                        "type": "MemberExpression",
                        "span": {
                          "start": 610,
                          "end": 625
                        },
                        "object": {
                          "type": "Identifier",
                          "span": {
                            "start": 610,
                            "end": 618
                          },
                          "ctxt": 3,
                          "value": "children",
                          "optional": false
                        },
                        "property": {
                          "type": "Identifier",
                          "span": {
                            "start": 619,
                            "end": 625
                          },
                          "value": "length"
                        }
                      },
                      "right": {
                        "type": "NumericLiteral",
                        "span": {
                          "start": 628,
                          "end": 629
                        },
                        "value": 0,
                        "raw": "0"
                      }
                    }
                  },
                  "right": {
                    "type": "ParenthesisExpression",
                    "span": {
                      "start": 633,
                      "end": 756
                    },
                    "expression": {
                      "type": "JSXElement",
                      "span": {
                        "start": 643,
                        "end": 748
                      },
                      "opening": {
                        "type": "JSXOpeningElement",
                        "name": {
                          "type": "Identifier",
                          "span": {
                            "start": 644,
                            "end": 652
                          },
                          "ctxt": 1,
                          "value": "template",
                          "optional": false
                        },
                        "span": {
                          "start": 643,
                          "end": 707
                        },
                        "attributes": [
                          {
                            "type": "JSXAttribute",
                            "span": {
                              "start": 653,
                              "end": 675
                            },
                            "name": {
                              "type": "Identifier",
                              "span": {
                                "start": 653,
                                "end": 657
                              },
                              "value": "type"
                            },
                            "value": {
                              "type": "StringLiteral",
                              "span": {
                                "start": 658,
                                "end": 675
                              },
                              "value": "forket/children",
                              "raw": "\"forket/children\""
                            }
                          },
                          {
                            "type": "JSXAttribute",
                            "span": {
                              "start": 676,
                              "end": 684
                            },
                            "name": {
                              "type": "Identifier",
                              "span": {
                                "start": 676,
                                "end": 678
                              },
                              "value": "id"
                            },
                            "value": {
                              "type": "StringLiteral",
                              "span": {
                                "start": 679,
                                "end": 684
                              },
                              "value": id,
                              "raw": "\"" + id + "\""
                            }
                          },
                          {
                            "type": "JSXAttribute",
                            "span": {
                              "start": 685,
                              "end": 706
                            },
                            "name": {
                              "type": "Identifier",
                              "span": {
                                "start": 685,
                                "end": 691
                              },
                              "value": "data-c"
                            },
                            "value": {
                              "type": "StringLiteral",
                              "span": {
                                "start": 692,
                                "end": 706
                              },
                              "value": componentName,
                              "raw": "\"" + componentName + "\""
                            }
                          }
                        ],
                        "selfClosing": false,
                        "typeArguments": null
                      },
                      "children": [
                        {
                          "type": "JSXText",
                          "span": {
                            "start": 707,
                            "end": 718
                          },
                          "value": "\n          ",
                          "raw": "\n          "
                        },
                        {
                          "type": "JSXExpressionContainer",
                          "span": {
                            "start": 718,
                            "end": 728
                          },
                          "expression": {
                            "type": "Identifier",
                            "span": {
                              "start": 719,
                              "end": 727
                            },
                            "ctxt": 3,
                            "value": "children",
                            "optional": false
                          }
                        },
                        {
                          "type": "JSXText",
                          "span": {
                            "start": 728,
                            "end": 737
                          },
                          "value": "\n        ",
                          "raw": "\n        "
                        }
                      ],
                      "closing": {
                        "type": "JSXClosingElement",
                        "span": {
                          "start": 737,
                          "end": 748
                        },
                        "name": {
                          "type": "Identifier",
                          "span": {
                            "start": 739,
                            "end": 747
                          },
                          "ctxt": 1,
                          "value": "template",
                          "optional": false
                        }
                      }
                    }
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 757,
                  "end": 764
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 764,
                  "end": 836
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 765,
                      "end": 773
                    },
                    "ctxt": 1,
                    "value": "template",
                    "optional": false
                  },
                  "span": {
                    "start": 764,
                    "end": 825
                  },
                  "attributes": [
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 774,
                        "end": 793
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 774,
                          "end": 778
                        },
                        "value": "type"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 779,
                          "end": 793
                        },
                        "value": "forket/start",
                        "raw": "\"forket/start\""
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 794,
                        "end": 802
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 794,
                          "end": 796
                        },
                        "value": "id"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 797,
                          "end": 802
                        },
                        "value": id,
                        "raw": "\"" + id + "\""
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 803,
                        "end": 824
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 803,
                          "end": 809
                        },
                        "value": "data-c"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 810,
                          "end": 824
                        },
                        "value": componentName,
                        "raw": "\"" + componentName + "\""
                      }
                    }
                  ],
                  "selfClosing": false,
                  "typeArguments": null
                },
                "children": [],
                "closing": {
                  "type": "JSXClosingElement",
                  "span": {
                    "start": 825,
                    "end": 836
                  },
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 827,
                      "end": 835
                    },
                    "ctxt": 1,
                    "value": "template",
                    "optional": false
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 836,
                  "end": 843
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 843,
                  "end": 890
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 844,
                      "end": 856
                    },
                    "ctxt": 1,
                    "value": componentName,
                    "optional": false
                  },
                  "span": {
                    "start": 843,
                    "end": 890
                  },
                  "attributes": [
                    {
                      "type": "SpreadElement",
                      "spread": {
                        "start": 858,
                        "end": 861
                      },
                      "arguments": {
                        "type": "Identifier",
                        "span": {
                          "start": 861,
                          "end": 866
                        },
                        "ctxt": 3,
                        "value": "props",
                        "optional": false
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 868,
                        "end": 887
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 868,
                          "end": 876
                        },
                        "value": "children"
                      },
                      "value": {
                        "type": "JSXExpressionContainer",
                        "span": {
                          "start": 877,
                          "end": 887
                        },
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 878,
                            "end": 886
                          },
                          "ctxt": 3,
                          "value": "children",
                          "optional": false
                        }
                      }
                    }
                  ],
                  "selfClosing": true,
                  "typeArguments": null
                },
                "children": [],
                "closing": null
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 890,
                  "end": 897
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 897,
                  "end": 967
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 898,
                      "end": 906
                    },
                    "ctxt": 1,
                    "value": "template",
                    "optional": false
                  },
                  "span": {
                    "start": 897,
                    "end": 956
                  },
                  "attributes": [
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 907,
                        "end": 924
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 907,
                          "end": 911
                        },
                        "value": "type"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 912,
                          "end": 924
                        },
                        "value": "forket/end",
                        "raw": "\"forket/end\""
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 925,
                        "end": 933
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 925,
                          "end": 927
                        },
                        "value": "id"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 928,
                          "end": 933
                        },
                        "value": id,
                        "raw": "\"" + id + "\""
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 934,
                        "end": 955
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 934,
                          "end": 940
                        },
                        "value": "data-c"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 941,
                          "end": 955
                        },
                        "value": componentName,
                        "raw": "\"" + componentName + "\""
                      }
                    }
                  ],
                  "selfClosing": false,
                  "typeArguments": null
                },
                "children": [],
                "closing": {
                  "type": "JSXClosingElement",
                  "span": {
                    "start": 956,
                    "end": 967
                  },
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 958,
                      "end": 966
                    },
                    "ctxt": 1,
                    "value": "template",
                    "optional": false
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 967,
                  "end": 972
                },
                "value": "\n    ",
                "raw": "\n    "
              }
            ],
            "closing": {
              "type": "JSXClosingFragment",
              "span": {
                "start": 972,
                "end": 975
              }
            }
          }
        }
      }
    ]
  },
  "generator": false,
  "async": false,
  "typeParameters": null,
  "returnType": null
}
}