/* This file is auto-generated by Forket. Don't change it manually. */

module.exports = function (id, componentName) {
  return {
  "type": "FunctionDeclaration",
  "identifier": {
    "type": "Identifier",
    "span": {
      "start": 10,
      "end": 30
    },
    "ctxt": 2,
    "value": componentName + "Boundary",
    "optional": false
  },
  "declare": false,
  "params": [
    {
      "type": "Parameter",
      "span": {
        "start": 31,
        "end": 36
      },
      "decorators": [],
      "pat": {
        "type": "Identifier",
        "span": {
          "start": 31,
          "end": 36
        },
        "ctxt": 3,
        "value": "props",
        "optional": false,
        "typeAnnotation": null
      }
    }
  ],
  "decorators": [],
  "span": {
    "start": 1,
    "end": 637
  },
  "ctxt": 3,
  "body": {
    "type": "BlockStatement",
    "span": {
      "start": 38,
      "end": 637
    },
    "ctxt": 3,
    "stmts": [
      {
        "type": "VariableDeclaration",
        "span": {
          "start": 42,
          "end": 105
        },
        "ctxt": 0,
        "kind": "const",
        "declare": false,
        "declarations": [
          {
            "type": "VariableDeclarator",
            "span": {
              "start": 48,
              "end": 104
            },
            "id": {
              "type": "Identifier",
              "span": {
                "start": 48,
                "end": 63
              },
              "ctxt": 3,
              "value": "serializedProps",
              "optional": false,
              "typeAnnotation": null
            },
            "init": {
              "type": "CallExpression",
              "span": {
                "start": 66,
                "end": 104
              },
              "ctxt": 0,
              "callee": {
                "type": "MemberExpression",
                "span": {
                  "start": 66,
                  "end": 80
                },
                "object": {
                  "type": "Identifier",
                  "span": {
                    "start": 66,
                    "end": 70
                  },
                  "ctxt": 1,
                  "value": "JSON",
                  "optional": false
                },
                "property": {
                  "type": "Identifier",
                  "span": {
                    "start": 71,
                    "end": 80
                  },
                  "value": "stringify"
                }
              },
              "arguments": [
                {
                  "spread": null,
                  "expression": {
                    "type": "CallExpression",
                    "span": {
                      "start": 81,
                      "end": 103
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "Identifier",
                      "span": {
                        "start": 81,
                        "end": 96
                      },
                      "ctxt": 1,
                      "value": "serialize$Props",
                      "optional": false
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 97,
                            "end": 102
                          },
                          "ctxt": 3,
                          "value": "props",
                          "optional": false
                        }
                      }
                    ],
                    "typeArguments": null
                  }
                }
              ],
              "typeArguments": null
            },
            "definite": false
          }
        ]
      },
      {
        "type": "VariableDeclaration",
        "span": {
          "start": 108,
          "end": 146
        },
        "ctxt": 0,
        "kind": "const",
        "declare": false,
        "declarations": [
          {
            "type": "VariableDeclarator",
            "span": {
              "start": 114,
              "end": 145
            },
            "id": {
              "type": "Identifier",
              "span": {
                "start": 114,
                "end": 122
              },
              "ctxt": 3,
              "value": "children",
              "optional": false,
              "typeAnnotation": null
            },
            "init": {
              "type": "BinaryExpression",
              "span": {
                "start": 125,
                "end": 145
              },
              "operator": "||",
              "left": {
                "type": "MemberExpression",
                "span": {
                  "start": 125,
                  "end": 139
                },
                "object": {
                  "type": "Identifier",
                  "span": {
                    "start": 125,
                    "end": 130
                  },
                  "ctxt": 3,
                  "value": "props",
                  "optional": false
                },
                "property": {
                  "type": "Identifier",
                  "span": {
                    "start": 131,
                    "end": 139
                  },
                  "value": "children"
                }
              },
              "right": {
                "type": "ArrayExpression",
                "span": {
                  "start": 143,
                  "end": 145
                },
                "elements": []
              }
            },
            "definite": false
          }
        ]
      },
      {
        "type": "ReturnStatement",
        "span": {
          "start": 149,
          "end": 635
        },
        "argument": {
          "type": "ParenthesisExpression",
          "span": {
            "start": 156,
            "end": 634
          },
          "expression": {
            "type": "JSXFragment",
            "span": {
              "start": 162,
              "end": 630
            },
            "opening": {
              "type": "JSXOpeningFragment",
              "span": {
                "start": 162,
                "end": 164
              }
            },
            "children": [
              {
                "type": "JSXText",
                "span": {
                  "start": 164,
                  "end": 171
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 171,
                  "end": 263
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 172,
                      "end": 184
                    },
                    "ctxt": 1,
                    "value": "boundary_" + id,
                    "optional": false
                  },
                  "span": {
                    "start": 171,
                    "end": 185
                  },
                  "attributes": [],
                  "selfClosing": false,
                  "typeArguments": null
                },
                "children": [
                  {
                    "type": "JSXText",
                    "span": {
                      "start": 185,
                      "end": 194
                    },
                    "value": "\n        ",
                    "raw": "\n        "
                  },
                  {
                    "type": "JSXElement",
                    "span": {
                      "start": 194,
                      "end": 241
                    },
                    "opening": {
                      "type": "JSXOpeningElement",
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 195,
                          "end": 207
                        },
                        "ctxt": 1,
                        "value": componentName,
                        "optional": false
                      },
                      "span": {
                        "start": 194,
                        "end": 241
                      },
                      "attributes": [
                        {
                          "type": "SpreadElement",
                          "spread": {
                            "start": 209,
                            "end": 212
                          },
                          "arguments": {
                            "type": "Identifier",
                            "span": {
                              "start": 212,
                              "end": 217
                            },
                            "ctxt": 3,
                            "value": "props",
                            "optional": false
                          }
                        },
                        {
                          "type": "JSXAttribute",
                          "span": {
                            "start": 219,
                            "end": 238
                          },
                          "name": {
                            "type": "Identifier",
                            "span": {
                              "start": 219,
                              "end": 227
                            },
                            "value": "children"
                          },
                          "value": {
                            "type": "JSXExpressionContainer",
                            "span": {
                              "start": 228,
                              "end": 238
                            },
                            "expression": {
                              "type": "Identifier",
                              "span": {
                                "start": 229,
                                "end": 237
                              },
                              "ctxt": 3,
                              "value": "children",
                              "optional": false
                            }
                          }
                        }
                      ],
                      "selfClosing": true,
                      "typeArguments": null
                    },
                    "children": [],
                    "closing": null
                  },
                  {
                    "type": "JSXText",
                    "span": {
                      "start": 241,
                      "end": 248
                    },
                    "value": "\n      ",
                    "raw": "\n      "
                  }
                ],
                "closing": {
                  "type": "JSXClosingElement",
                  "span": {
                    "start": 248,
                    "end": 263
                  },
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 250,
                      "end": 262
                    },
                    "ctxt": 1,
                    "value": "boundary_" + id,
                    "optional": false
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 263,
                  "end": 270
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 270,
                  "end": 622
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 271,
                      "end": 277
                    },
                    "ctxt": 1,
                    "value": "script",
                    "optional": false
                  },
                  "span": {
                    "start": 270,
                    "end": 622
                  },
                  "attributes": [
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 286,
                        "end": 613
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 286,
                          "end": 309
                        },
                        "value": "dangerouslySetInnerHTML"
                      },
                      "value": {
                        "type": "JSXExpressionContainer",
                        "span": {
                          "start": 310,
                          "end": 613
                        },
                        "expression": {
                          "type": "ObjectExpression",
                          "span": {
                            "start": 311,
                            "end": 612
                          },
                          "properties": [
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 323,
                                  "end": 329
                                },
                                "value": "__html"
                              },
                              "value": {
                                "type": "TemplateLiteral",
                                "span": {
                                  "start": 331,
                                  "end": 602
                                },
                                "expressions": [
                                  {
                                    "type": "Identifier",
                                    "span": {
                                      "start": 375,
                                      "end": 390
                                    },
                                    "ctxt": 3,
                                    "value": "serializedProps",
                                    "optional": false
                                  }
                                ],
                                "quasis": [
                                  {
                                    "type": "TemplateElement",
                                    "span": {
                                      "start": 332,
                                      "end": 373
                                    },
                                    "tail": false,
                                    "cooked": "(function () {\n  const serializedProps = ",
                                    "raw": "(function () {\n  const serializedProps = "
                                  },
                                  {
                                    "type": "TemplateElement",
                                    "span": {
                                      "start": 391,
                                      "end": 601
                                    },
                                    "tail": true,
                                    "cooked": ";\n  if (typeof $FRSC !== 'undefined') return $FRSC([\"" + id + "\", \"" + componentName + "\", serializedProps]);\n  if (typeof $FRSC_ === 'undefined') { $FRSC_ = []; }\n  $FRSC_.push([\"" + id + "\", \"" + componentName + "\", serializedProps]);\n})();",
                                    "raw": ";\n  if (typeof $FRSC !== 'undefined') return $FRSC([\"" + id + "\", \"" + componentName + "\", serializedProps]);\n  if (typeof $FRSC_ === 'undefined') { $FRSC_ = []; }\n  $FRSC_.push([\"" + id + "\", \"" + componentName + "\", serializedProps]);\n})();"
                                  }
                                ]
                              }
                            }
                          ]
                        }
                      }
                    }
                  ],
                  "selfClosing": true,
                  "typeArguments": null
                },
                "children": [],
                "closing": null
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 622,
                  "end": 627
                },
                "value": "\n    ",
                "raw": "\n    "
              }
            ],
            "closing": {
              "type": "JSXClosingFragment",
              "span": {
                "start": 627,
                "end": 630
              }
            }
          }
        }
      }
    ]
  },
  "generator": false,
  "async": false,
  "typeParameters": null,
  "returnType": null
}
}