/* This file is auto-generated by Forket. Don't change it manually. */

export default function (id, componentName) {
  return {
  "type": "FunctionDeclaration",
  "identifier": {
    "type": "Identifier",
    "span": {
      "start": 10,
      "end": 23
    },
    "ctxt": 2,
    "value": componentName + "Boundary",
    "optional": false
  },
  "declare": false,
  "params": [
    {
      "type": "Parameter",
      "span": {
        "start": 24,
        "end": 29
      },
      "decorators": [],
      "pat": {
        "type": "Identifier",
        "span": {
          "start": 24,
          "end": 29
        },
        "ctxt": 3,
        "value": "props",
        "optional": false,
        "typeAnnotation": null
      }
    }
  ],
  "decorators": [],
  "span": {
    "start": 1,
    "end": 2353
  },
  "ctxt": 3,
  "body": {
    "type": "BlockStatement",
    "span": {
      "start": 31,
      "end": 2353
    },
    "ctxt": 3,
    "stmts": [
      {
        "type": "VariableDeclaration",
        "span": {
          "start": 35,
          "end": 126
        },
        "ctxt": 0,
        "kind": "const",
        "declare": false,
        "declarations": [
          {
            "type": "VariableDeclarator",
            "span": {
              "start": 41,
              "end": 125
            },
            "id": {
              "type": "Identifier",
              "span": {
                "start": 41,
                "end": 56
              },
              "ctxt": 3,
              "value": "serializedProps",
              "optional": false,
              "typeAnnotation": null
            },
            "init": {
              "type": "CallExpression",
              "span": {
                "start": 59,
                "end": 125
              },
              "ctxt": 0,
              "callee": {
                "type": "MemberExpression",
                "span": {
                  "start": 59,
                  "end": 73
                },
                "object": {
                  "type": "Identifier",
                  "span": {
                    "start": 59,
                    "end": 63
                  },
                  "ctxt": 1,
                  "value": "JSON",
                  "optional": false
                },
                "property": {
                  "type": "Identifier",
                  "span": {
                    "start": 64,
                    "end": 73
                  },
                  "value": "stringify"
                }
              },
              "arguments": [
                {
                  "spread": null,
                  "expression": {
                    "type": "CallExpression",
                    "span": {
                      "start": 74,
                      "end": 124
                    },
                    "ctxt": 0,
                    "callee": {
                      "type": "Identifier",
                      "span": {
                        "start": 74,
                        "end": 94
                      },
                      "ctxt": 1,
                      "value": "forketSerializeProps",
                      "optional": false
                    },
                    "arguments": [
                      {
                        "spread": null,
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 95,
                            "end": 100
                          },
                          "ctxt": 3,
                          "value": "props",
                          "optional": false
                        }
                      },
                      {
                        "spread": null,
                        "expression": {
                          "type": "StringLiteral",
                          "span": {
                            "start": 102,
                            "end": 116
                          },
                          "value": componentName,
                          "raw": "\"" + componentName + "\""
                        }
                      },
                      {
                        "spread": null,
                        "expression": {
                          "type": "StringLiteral",
                          "span": {
                            "start": 118,
                            "end": 123
                          },
                          "value": id,
                          "raw": "\"" + id + "\""
                        }
                      }
                    ],
                    "typeArguments": null
                  }
                }
              ],
              "typeArguments": null
            },
            "definite": false
          }
        ]
      },
      {
        "type": "VariableDeclaration",
        "span": {
          "start": 129,
          "end": 161
        },
        "ctxt": 0,
        "kind": "const",
        "declare": false,
        "declarations": [
          {
            "type": "VariableDeclarator",
            "span": {
              "start": 135,
              "end": 160
            },
            "id": {
              "type": "Identifier",
              "span": {
                "start": 135,
                "end": 143
              },
              "ctxt": 3,
              "value": "children",
              "optional": false,
              "typeAnnotation": null
            },
            "init": {
              "type": "MemberExpression",
              "span": {
                "start": 146,
                "end": 160
              },
              "object": {
                "type": "Identifier",
                "span": {
                  "start": 146,
                  "end": 151
                },
                "ctxt": 3,
                "value": "props",
                "optional": false
              },
              "property": {
                "type": "Identifier",
                "span": {
                  "start": 152,
                  "end": 160
                },
                "value": "children"
              }
            },
            "definite": false
          }
        ]
      },
      {
        "type": "ReturnStatement",
        "span": {
          "start": 164,
          "end": 2351
        },
        "argument": {
          "type": "ParenthesisExpression",
          "span": {
            "start": 171,
            "end": 2350
          },
          "expression": {
            "type": "JSXFragment",
            "span": {
              "start": 177,
              "end": 2346
            },
            "opening": {
              "type": "JSXOpeningFragment",
              "span": {
                "start": 177,
                "end": 179
              }
            },
            "children": [
              {
                "type": "JSXText",
                "span": {
                  "start": 179,
                  "end": 186
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXExpressionContainer",
                "span": {
                  "start": 186,
                  "end": 323
                },
                "expression": {
                  "type": "BinaryExpression",
                  "span": {
                    "start": 187,
                    "end": 322
                  },
                  "operator": "&&",
                  "left": {
                    "type": "Identifier",
                    "span": {
                      "start": 187,
                      "end": 195
                    },
                    "ctxt": 3,
                    "value": "children",
                    "optional": false
                  },
                  "right": {
                    "type": "ParenthesisExpression",
                    "span": {
                      "start": 199,
                      "end": 322
                    },
                    "expression": {
                      "type": "JSXElement",
                      "span": {
                        "start": 209,
                        "end": 314
                      },
                      "opening": {
                        "type": "JSXOpeningElement",
                        "name": {
                          "type": "Identifier",
                          "span": {
                            "start": 210,
                            "end": 218
                          },
                          "ctxt": 1,
                          "value": "template",
                          "optional": false
                        },
                        "span": {
                          "start": 209,
                          "end": 273
                        },
                        "attributes": [
                          {
                            "type": "JSXAttribute",
                            "span": {
                              "start": 219,
                              "end": 241
                            },
                            "name": {
                              "type": "Identifier",
                              "span": {
                                "start": 219,
                                "end": 223
                              },
                              "value": "type"
                            },
                            "value": {
                              "type": "StringLiteral",
                              "span": {
                                "start": 224,
                                "end": 241
                              },
                              "value": "forket/children",
                              "raw": "\"forket/children\""
                            }
                          },
                          {
                            "type": "JSXAttribute",
                            "span": {
                              "start": 242,
                              "end": 250
                            },
                            "name": {
                              "type": "Identifier",
                              "span": {
                                "start": 242,
                                "end": 244
                              },
                              "value": "id"
                            },
                            "value": {
                              "type": "StringLiteral",
                              "span": {
                                "start": 245,
                                "end": 250
                              },
                              "value": id,
                              "raw": "\"" + id + "\""
                            }
                          },
                          {
                            "type": "JSXAttribute",
                            "span": {
                              "start": 251,
                              "end": 272
                            },
                            "name": {
                              "type": "Identifier",
                              "span": {
                                "start": 251,
                                "end": 257
                              },
                              "value": "data-c"
                            },
                            "value": {
                              "type": "StringLiteral",
                              "span": {
                                "start": 258,
                                "end": 272
                              },
                              "value": componentName,
                              "raw": "\"" + componentName + "\""
                            }
                          }
                        ],
                        "selfClosing": false,
                        "typeArguments": null
                      },
                      "children": [
                        {
                          "type": "JSXText",
                          "span": {
                            "start": 273,
                            "end": 284
                          },
                          "value": "\n          ",
                          "raw": "\n          "
                        },
                        {
                          "type": "JSXExpressionContainer",
                          "span": {
                            "start": 284,
                            "end": 294
                          },
                          "expression": {
                            "type": "Identifier",
                            "span": {
                              "start": 285,
                              "end": 293
                            },
                            "ctxt": 3,
                            "value": "children",
                            "optional": false
                          }
                        },
                        {
                          "type": "JSXText",
                          "span": {
                            "start": 294,
                            "end": 303
                          },
                          "value": "\n        ",
                          "raw": "\n        "
                        }
                      ],
                      "closing": {
                        "type": "JSXClosingElement",
                        "span": {
                          "start": 303,
                          "end": 314
                        },
                        "name": {
                          "type": "Identifier",
                          "span": {
                            "start": 305,
                            "end": 313
                          },
                          "ctxt": 1,
                          "value": "template",
                          "optional": false
                        }
                      }
                    }
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 323,
                  "end": 330
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 330,
                  "end": 397
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 331,
                      "end": 339
                    },
                    "ctxt": 1,
                    "value": "template",
                    "optional": false
                  },
                  "span": {
                    "start": 330,
                    "end": 386
                  },
                  "attributes": [
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 340,
                        "end": 363
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 340,
                          "end": 344
                        },
                        "value": "type"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 345,
                          "end": 363
                        },
                        "value": "forket/start/" + id + "",
                        "raw": "\"forket/start/" + id + "\""
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 364,
                        "end": 385
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 364,
                          "end": 370
                        },
                        "value": "data-c"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 371,
                          "end": 385
                        },
                        "value": componentName,
                        "raw": "\"" + componentName + "\""
                      }
                    }
                  ],
                  "selfClosing": false,
                  "typeArguments": null
                },
                "children": [],
                "closing": {
                  "type": "JSXClosingElement",
                  "span": {
                    "start": 386,
                    "end": 397
                  },
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 388,
                      "end": 396
                    },
                    "ctxt": 1,
                    "value": "template",
                    "optional": false
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 397,
                  "end": 404
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 404,
                  "end": 451
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 405,
                      "end": 417
                    },
                    "ctxt": 1,
                    "value": componentName,
                    "optional": false
                  },
                  "span": {
                    "start": 404,
                    "end": 451
                  },
                  "attributes": [
                    {
                      "type": "SpreadElement",
                      "spread": {
                        "start": 419,
                        "end": 422
                      },
                      "arguments": {
                        "type": "Identifier",
                        "span": {
                          "start": 422,
                          "end": 427
                        },
                        "ctxt": 3,
                        "value": "props",
                        "optional": false
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 429,
                        "end": 448
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 429,
                          "end": 437
                        },
                        "value": "children"
                      },
                      "value": {
                        "type": "JSXExpressionContainer",
                        "span": {
                          "start": 438,
                          "end": 448
                        },
                        "expression": {
                          "type": "Identifier",
                          "span": {
                            "start": 439,
                            "end": 447
                          },
                          "ctxt": 3,
                          "value": "children",
                          "optional": false
                        }
                      }
                    }
                  ],
                  "selfClosing": true,
                  "typeArguments": null
                },
                "children": [],
                "closing": null
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 451,
                  "end": 458
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 458,
                  "end": 523
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 459,
                      "end": 467
                    },
                    "ctxt": 1,
                    "value": "template",
                    "optional": false
                  },
                  "span": {
                    "start": 458,
                    "end": 512
                  },
                  "attributes": [
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 468,
                        "end": 489
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 468,
                          "end": 472
                        },
                        "value": "type"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 473,
                          "end": 489
                        },
                        "value": "forket/end/" + id + "",
                        "raw": "\"forket/end/" + id + "\""
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 490,
                        "end": 511
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 490,
                          "end": 496
                        },
                        "value": "data-c"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 497,
                          "end": 511
                        },
                        "value": componentName,
                        "raw": "\"" + componentName + "\""
                      }
                    }
                  ],
                  "selfClosing": false,
                  "typeArguments": null
                },
                "children": [],
                "closing": {
                  "type": "JSXClosingElement",
                  "span": {
                    "start": 512,
                    "end": 523
                  },
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 514,
                      "end": 522
                    },
                    "ctxt": 1,
                    "value": "template",
                    "optional": false
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 523,
                  "end": 530
                },
                "value": "\n      ",
                "raw": "\n      "
              },
              {
                "type": "JSXElement",
                "span": {
                  "start": 530,
                  "end": 2338
                },
                "opening": {
                  "type": "JSXOpeningElement",
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 531,
                      "end": 537
                    },
                    "ctxt": 1,
                    "value": "script",
                    "optional": false
                  },
                  "span": {
                    "start": 530,
                    "end": 2329
                  },
                  "attributes": [
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 546,
                        "end": 566
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 546,
                          "end": 548
                        },
                        "value": "id"
                      },
                      "value": {
                        "type": "StringLiteral",
                        "span": {
                          "start": 549,
                          "end": 566
                        },
                        "value": "forket/init/" + id + "",
                        "raw": "\"forket/init/" + id + "\""
                      }
                    },
                    {
                      "type": "JSXAttribute",
                      "span": {
                        "start": 575,
                        "end": 2321
                      },
                      "name": {
                        "type": "Identifier",
                        "span": {
                          "start": 575,
                          "end": 598
                        },
                        "value": "dangerouslySetInnerHTML"
                      },
                      "value": {
                        "type": "JSXExpressionContainer",
                        "span": {
                          "start": 599,
                          "end": 2321
                        },
                        "expression": {
                          "type": "ObjectExpression",
                          "span": {
                            "start": 600,
                            "end": 2320
                          },
                          "properties": [
                            {
                              "type": "KeyValueProperty",
                              "key": {
                                "type": "Identifier",
                                "span": {
                                  "start": 612,
                                  "end": 618
                                },
                                "value": "__html"
                              },
                              "value": {
                                "type": "TemplateLiteral",
                                "span": {
                                  "start": 620,
                                  "end": 2310
                                },
                                "expressions": [
                                  {
                                    "type": "CallExpression",
                                    "span": {
                                      "start": 710,
                                      "end": 741
                                    },
                                    "ctxt": 0,
                                    "callee": {
                                      "type": "MemberExpression",
                                      "span": {
                                        "start": 710,
                                        "end": 724
                                      },
                                      "object": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 710,
                                          "end": 714
                                        },
                                        "ctxt": 1,
                                        "value": "JSON",
                                        "optional": false
                                      },
                                      "property": {
                                        "type": "Identifier",
                                        "span": {
                                          "start": 715,
                                          "end": 724
                                        },
                                        "value": "stringify"
                                      }
                                    },
                                    "arguments": [
                                      {
                                        "spread": null,
                                        "expression": {
                                          "type": "Identifier",
                                          "span": {
                                            "start": 725,
                                            "end": 740
                                          },
                                          "ctxt": 3,
                                          "value": "serializedProps",
                                          "optional": false
                                        }
                                      }
                                    ],
                                    "typeArguments": null
                                  }
                                ],
                                "quasis": [
                                  {
                                    "type": "TemplateElement",
                                    "span": {
                                      "start": 621,
                                      "end": 708
                                    },
                                    "tail": false,
                                    "cooked": "(function () {\n          function init() {\n            let a = [\"" + id + "\", \"" + componentName + "\", ",
                                    "raw": "(function () {\n          function init() {\n            let a = [\"" + id + "\", \"" + componentName + "\", "
                                  },
                                  {
                                    "type": "TemplateElement",
                                    "span": {
                                      "start": 742,
                                      "end": 2309
                                    },
                                    "tail": true,
                                    "cooked": "];\n            if (typeof window.$FRSC === 'function') {\n              $F_logs(\"‎𐂐 [server] <" + componentName + "> (" + id + ") streaming done. Hydration in flight ...\");\n              window.$FRSC(a);\n            } else {\n              if (typeof $FRSC_ === 'undefined') {\n                $FRSC_ = [];\n              }\n              $F_logs(\"‎𐂐 [server] <" + componentName + "> (" + id + ") streaming done.\");\n              $FRSC_.push(a);\n            }\n            let me = document.currentScript;\n            if (me) me.remove();\n          }\n          if (document.currentScript.closest(\"div[hidden]\")) {\n            const observer = new MutationObserver((mutationsList) => {\n              for(let i=0; i<mutationsList.length; i++) {\n                const added = mutationsList[i].addedNodes;\n                for(let j=0; j<added.length; j++) {\n                  const n = added[j];\n                  if (n.nodeType !== 1) continue;\n                  if (n.getAttribute) {\n                    const scriptNode = n.getAttribute('id') === 'forket/init/" + id + "' || n.querySelector('[id=\"forket/init/" + id + "\"]');\n                    if (scriptNode) {\n                      init();\n                      observer.disconnect();\n                      scriptNode.remove();\n                      return;\n                    }\n                  }\n                }\n              }\n            });\n            observer.observe(\n              document.documentElement,\n              { childList: true, subtree: true }\n            );\n          } else {\n            init();\n          }\n        })();\n        ",
                                    "raw": "];\n            if (typeof window.$FRSC === 'function') {\n              $F_logs(\"‎𐂐 [server] <" + componentName + "> (" + id + ") streaming done. Hydration in flight ...\");\n              window.$FRSC(a);\n            } else {\n              if (typeof $FRSC_ === 'undefined') {\n                $FRSC_ = [];\n              }\n              $F_logs(\"‎𐂐 [server] <" + componentName + "> (" + id + ") streaming done.\");\n              $FRSC_.push(a);\n            }\n            let me = document.currentScript;\n            if (me) me.remove();\n          }\n          if (document.currentScript.closest(\"div[hidden]\")) {\n            const observer = new MutationObserver((mutationsList) => {\n              for(let i=0; i<mutationsList.length; i++) {\n                const added = mutationsList[i].addedNodes;\n                for(let j=0; j<added.length; j++) {\n                  const n = added[j];\n                  if (n.nodeType !== 1) continue;\n                  if (n.getAttribute) {\n                    const scriptNode = n.getAttribute('id') === 'forket/init/" + id + "' || n.querySelector('[id=\"forket/init/" + id + "\"]');\n                    if (scriptNode) {\n                      init();\n                      observer.disconnect();\n                      scriptNode.remove();\n                      return;\n                    }\n                  }\n                }\n              }\n            });\n            observer.observe(\n              document.documentElement,\n              { childList: true, subtree: true }\n            );\n          } else {\n            init();\n          }\n        })();\n        "
                                  }
                                ]
                              }
                            }
                          ]
                        }
                      }
                    }
                  ],
                  "selfClosing": false,
                  "typeArguments": null
                },
                "children": [],
                "closing": {
                  "type": "JSXClosingElement",
                  "span": {
                    "start": 2329,
                    "end": 2338
                  },
                  "name": {
                    "type": "Identifier",
                    "span": {
                      "start": 2331,
                      "end": 2337
                    },
                    "ctxt": 1,
                    "value": "script",
                    "optional": false
                  }
                }
              },
              {
                "type": "JSXText",
                "span": {
                  "start": 2338,
                  "end": 2343
                },
                "value": "\n    ",
                "raw": "\n    "
              }
            ],
            "closing": {
              "type": "JSXClosingFragment",
              "span": {
                "start": 2343,
                "end": 2346
              }
            }
          }
        }
      }
    ]
  },
  "generator": false,
  "async": false,
  "typeParameters": null,
  "returnType": null
}
}