/* This file is auto-generated by Forket. Don't change it manually. */

export default function (what, where, specifier = "ImportDefaultSpecifier") {
  return [
  {
    "type": "ImportDeclaration",
    "span": {
      "start": 1140,
      "end": 1166
    },
    "specifiers": [
      {
        "type": specifier,
        "span": {
          "start": 1147,
          "end": 1152
        },
        "local": {
          "type": "Identifier",
          "span": {
            "start": 1147,
            "end": 1152
          },
          "ctxt": 2,
          "value": what,
          "optional": false
        }
      }
    ],
    "source": {
      "type": "StringLiteral",
      "span": {
        "start": 1158,
        "end": 1165
      },
      "value": where,
      "raw": "\"" + where + "\""
    },
    "typeOnly": false,
    "with": null,
    "phase": "evaluation"
  }
]
}