/* This file is auto-generated by Forket. Don't change it manually. */

export default function (what, where, specifier = "ImportDefaultSpecifier") {
  return [
  {
    "type": "ImportDeclaration",
    "span": {
      "start": 1075,
      "end": 1101
    },
    "specifiers": [
      {
        "type": specifier,
        "span": {
          "start": 1082,
          "end": 1087
        },
        "local": {
          "type": "Identifier",
          "span": {
            "start": 1082,
            "end": 1087
          },
          "ctxt": 2,
          "value": what,
          "optional": false
        }
      }
    ],
    "source": {
      "type": "StringLiteral",
      "span": {
        "start": 1093,
        "end": 1100
      },
      "value": where,
      "raw": "\"" + where + "\""
    },
    "typeOnly": false,
    "with": null,
    "phase": "evaluation"
  }
]
}