/* This file is auto-generated by Forket. Don't change it manually. */

module.exports = function () {
  return [
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 1,
      "end": 32
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 7,
          "end": 31
        },
        "id": {
          "type": "Identifier",
          "span": {
            "start": 7,
            "end": 12
          },
          "ctxt": 2,
          "value": "React",
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "CallExpression",
          "span": {
            "start": 15,
            "end": 31
          },
          "ctxt": 0,
          "callee": {
            "type": "Identifier",
            "span": {
              "start": 15,
              "end": 22
            },
            "ctxt": 1,
            "value": "require",
            "optional": false
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "StringLiteral",
                "span": {
                  "start": 23,
                  "end": 30
                },
                "value": "react",
                "raw": "\"react\""
              }
            }
          ],
          "typeArguments": null
        },
        "definite": false
      }
    ]
  },
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 33,
      "end": 84
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 39,
          "end": 83
        },
        "id": {
          "type": "Identifier",
          "span": {
            "start": 39,
            "end": 53
          },
          "ctxt": 2,
          "value": "ReactDOMClient",
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "CallExpression",
          "span": {
            "start": 56,
            "end": 83
          },
          "ctxt": 0,
          "callee": {
            "type": "Identifier",
            "span": {
              "start": 56,
              "end": 63
            },
            "ctxt": 1,
            "value": "require",
            "optional": false
          },
          "arguments": [
            {
              "spread": null,
              "expression": {
                "type": "StringLiteral",
                "span": {
                  "start": 64,
                  "end": 82
                },
                "value": "react-dom/client",
                "raw": "\"react-dom/client\""
              }
            }
          ],
          "typeArguments": null
        },
        "definite": false
      }
    ]
  }
]
}