/* This file is auto-generated by Forket. Don't change it manually. */

export default function (variableName, values) {
  return [
  {
    "type": "VariableDeclaration",
    "span": {
      "start": 1252,
      "end": 1309
    },
    "ctxt": 0,
    "kind": "const",
    "declare": false,
    "declarations": [
      {
        "type": "VariableDeclarator",
        "span": {
          "start": 1258,
          "end": 1309
        },
        "id": {
          "type": "Identifier",
          "span": {
            "start": 1258,
            "end": 1265
          },
          "ctxt": 2,
          "value": variableName,
          "optional": false,
          "typeAnnotation": null
        },
        "init": {
          "type": "ObjectExpression",
          "span": {
            "start": 1268,
            "end": 1309
          },
          "properties": values.map(v => {
          return {
            "type": "KeyValueProperty",
            "key": {
              "type": "Identifier",
              "span": {
                "start": 884,
                "end": 888
              },
              "value": v[0]
            },
            "value": {
              "type": "Identifier",
              "span": {
                "start": 890,
                "end": 899
              },
              "ctxt": 1,
              "value": v[1],
              "optional": false
            }
          };
        })
        },
        "definite": false
      }
    ]
  }
]
}